### ISSUE TITLE
fix line height

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/three-mesh-ui#110]
#106 introduced an issue with lines height : 
![Screenshot_1](https://user-images.githubusercontent.com/46470486/147674483-c8a7c81f-d0e9-47c6-ad75-f7d379eca366.jpg)

**Comment by felixmariotto** [comment]
fixed with 6.0.2

**Comment by swingingtom** [comment]
Thanks @felixmariotto it looks really better !
