### ISSUE TITLE
Cannot initialize on IOS with Expo SDK 43

### ISSUE THREAD

**Issue by jaymes-bearden** [felixmariotto/three-mesh-ui#126]
After adding `three-mesh-ui@6.0.3` and importing, I cannot start app due to immediate initialization in `src/utils/Defaults.js::DefaultBackgroundTexture()`.

Is it possible to adjust this code to lazy initialize to give us a chance to override?

![Image from iOS](https://user-images.githubusercontent.com/423664/150022432-fd0dbbe2-0bf4-40ad-b5eb-053849cf4c40.png)

**Comment by felixmariotto** [comment]
Hi @jaymes-bearden, would PR #127 work for you ?

**Comment by felixmariotto** [comment]
Hi @jaymes-bearden , would PR #127 work for you ?

**Comment by jaymes-bearden** [comment]
@felixmariotto That works perfectly! Thank you 👍
