### ISSUE TITLE
MaterialManager refactor

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/three-mesh-ui#130]
Hi all,

While working on the font antialiasing, I realized that there is an problem with [MaterialManager](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/MaterialManager.js).

@hybridherbst proposed a performance improvement [here](https://github.com/felixmariotto/three-mesh-ui/pull/125#issuecomment-1017284918) that require precomputing a value to set as uniform. But where should this precomputing take place ? In `_makeTextMaterial` ? In `getFontMaterial` ? in `updateTextMaterial` ?

This is the issue that @Enijar faced when implementing variable border radius, they had to duplicate code in three functions of the module.

To fix this issue I propose that `this.backgroundUniforms` and `this.textUniforms` be set in `MaterialManager` constructor, and only one function should be in charge of calling `this.getFontOpacity()` and such to update `this.textUniforms`.

**Comment by swingingtom** [comment]
> To fix this issue I propose that this.backgroundUniforms and this.textUniforms be set in MaterialManager constructor, and only one function should be in charge of calling this.getFontOpacity() and such to update this.textUniforms.

Is the idea of this issue to explicitely focus on that proposal or / also to open a discussion about a wider refactor ?

**Comment by felixmariotto** [comment]
It's really a problem with MaterialManager here, but feel free to open another issue to propose a more general refactor.
