### ISSUE TITLE
Russian layout

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/three-mesh-ui#15]
So I understand from [this](https://en.m.wikipedia.org/wiki/JCUKEN) that the layout to aim for is the JCUKEN layout.

As english is very common on the internet, I suppose that you guys need to switch from time to time to access "missing" letters like N.

How do you do with the physical keyboard ? What would be a convenient way of doing it with this virtual keyboard ?

**Comment by Dragon3DGraff** [comment]
![image](https://user-images.githubusercontent.com/51860375/82912879-42915700-9f76-11ea-82f1-84581d795386.png)
you can do it like this
and one key to switch between languages

**Comment by felixmariotto** [comment]
I see, I will do that.

Let's say you're in QWERTY mode, the English letters in the top left of the keys would be bigger and whiter, to better understand which set of letters is on. Does it sound right ?

Another thing, on the right of the keyboard you sent, some keys have a Russian letter, but symbols instead of English letters (since there is more in Russian). Are these symbols a standard, or can I change, let's say for basic punctuation like " ? ! : ' " ?

**Comment by felixmariotto** [comment]
![2020-05-28_151314](https://user-images.githubusercontent.com/46470486/83147218-adb66700-a0f7-11ea-8d60-b9ba96ae863c.jpg)

Is that right ? The 'eng' key will switch with English

**Comment by Dragon3DGraff** [comment]
yeah, this cool! exactly what is needed
only swap "Э" and "З"

**Comment by Dragon3DGraff** [comment]
> symbols a standard

Yes, symbols are standard

**Comment by felixmariotto** [comment]
Great, thanks a lot

**Comment by felixmariotto** [comment]
It’s now live :
https://three-mesh-ui.herokuapp.com/#keyboard ( click on ‘Russian’ )

Thanks again !
