### ISSUE TITLE
updateLayout being called on components whose layout isn't updated

### ISSUE THREAD

**Issue by dmliao** [felixmariotto/three-mesh-ui#150]
I was noticing performance issues when creating a UI panel that faded into the scene, and saw from profiling that `updateLayout` was being called every single frame for the components, even though the layout hadn't been changed. 

Further digging suggests that this is a result of https://github.com/felixmariotto/three-mesh-ui/blob/83b9e52e818bf682de3b707e41ad9e9654fb9aa1/src/components/core/MeshUIComponent.js#L483 -- by default, `parent.getBestFit()` will always be true since it's set to 'none' by default -- which is truthy, causing an updateLayout call with every update.

**Comment by GoncaloBastos** [comment]
Hi @dmliao there's already a PR open with this fix here #141. Just waiting for @felixmariotto to merge it in!

**Comment by felixmariotto** [comment]
@GoncaloBastos thank you for the fix, it's published as 6.3.0
