### ISSUE TITLE
Refactor FontLibrary

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/three-mesh-ui#153]
Currently [FontLibrary](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/FontLibrary.js) is a mess because there is two ways to add a font for the user: providing the texture and JSON directly OR passing URLs to let `FontLibrary` load them.

It's not easy to maintain, so @swingingtom and I think that we should ditch the option to let `FontLibrary` load the files. Since the user would have to load them, it would make the minimal code a bit larger though. All examples will have to be updated.

We would also create a `Font` class to separate concerns and ease further development.

**Comment by swingingtom** [comment]
Im not sure totally ditching the option to load font for users would be well received. But we could offer a uniformized way of registering fonts.

As soon as we will have a FontClass, we could dispatch events that could be caught by component that use them. That will remove the fact that currently font library execute functions in components when texture and json are loaded.

**Proposal**

ThreeMeshUI.FontLibrary.addFont(family,json,texture,style,weight) 
ThreeMeshUI.FontLIbrary.getFont(family,style,weight) returns a FontClass|null

```javascript
// Preferred way, providing loaded assets before creating any component
ThreeMeshUI.FontLibrary.addFont(fontFamily, loadedJson, loadedTexture, [style], [weight]);

// created component below would have access to a FontClass where texture and json are ready to be used
new ThreeMeshUI.Text({content:"..."})
```
```javascript
// Relying on three-mesh-ui to synchronously load assets before creating any component

// an async iife or function container would be required
(async ()=>{

await ThreeMeshUI.FontLibrary.addFont(fontFamily, jsonURL, textureURL, [style],[weight);

// created component below would have access to a FontClass where texture and json are ready to be used
new ThreeMeshUI.Text({content:"..."})

})();
```

```javascript
// Relying on three-mesh-ui to asynchronously load assets 

ThreeMeshUI.FontLibrary.addFont(fontFamily, jsonURL, textureURL, [style],[weight);

// created component below would have access to a FontClass where texture and json ARE NOT READY to be used
new ThreeMeshUI.Text({fontFamily:"Roboto", fontStyle:"italic", content:"..."})

// Internally Text component would ask ThreeMeshUI.FontLibrary.getFont() to obtain its FontClass
const font = ThreeMeshUI.FontLibrary.getFont("Roboto").getVariant("italic");
if( !font.isLoaded ){
   font.addEventListener("load", ()=>{ this.parent.triggerUpdate });
}
```

```javascript
// Relying on three-mesh-ui to asynchronously load assets from three-mesh-ui component
// actual support

// created component below would have access to a FontClass where texture and json are ready to be used
new ThreeMeshUI.Text({fontFamily:"jsonURL", fontTexture: "textureURL",content:"..."})

// Internally Text component would ask ThreeMeshUI.FontLibrary.getFont() to obtain its FontClass
let font = ThreeMeshUI.FontLibrary.getFont(jsonURL); // getProperty from parent
if( !font ){
 font = ThreeMeshUI.FontLibrary.addFont( jsonURL, jsonURL, textureURL);
}

font = font.getVariant("italic")

if( !font.isLoaded ){
   font.addEventListener("load", ()=>{ this.parent.triggerUpdate });
}
```

This defines more ways than we actually have, but they are all centralized on ThreeMeshUI.addFont. Which means we could still keep the commonly used behaviour to define font in parent block.

**1-2-3** acts like a setup.
**2** Might be restrictive for standard users
**4** differs from others, but offer the possibility to keep current behaviour. It has a conflict on the fontFamily property, which would act as an fontId but currently is a json object.
