### ISSUE TITLE
Combining manual positioning and hidden overflow?

### ISSUE THREAD

**Issue by kevinjardine** [felixmariotto/three-mesh-ui#155]
I'm trying to create a scrolling display like LED displays on trains by combining manual positioning to move the text with hidden overflow turned on.

But the text container is not clipped outside the parent container as I thought it would be with hiddenOverflow: true.

Is this feature supported?

![scrolling_display](https://user-images.githubusercontent.com/390782/152786433-378c8057-e3d7-4409-a616-69ab83e9742b.png)

**Comment by swingingtom** [comment]
Hey @kevinjardine 
I tried to reproduce your setup on [codesandbox](https://codesandbox.io/s/text-clipping-planes-1ynlx?file=/src/sandbox.js), and what I can confirm, is that `overflowHidden` property seems to have some requirements.

I succeed to make it work, but it required the following structure : 
- Block : OverflowHidden true
    - Child Block
        - Text Element
I can offset both ChildBlock and Text Element 

I didnt' succeed to make it work for : 
- Block : OverflowHidden
    - Text Element

I guess we cannot clip a text which is direct child of the `overflowHidden` parent. @felixmariotto could you confirm that?

Also, just to be sure, did you set `renderer.localClippingEnabled = true;`

**Comment by kevinjardine** [comment]
Thank you!

renderer.localClippingEnabled = true;

seems to have been what I overlooked in the hidden_overflow.js example.

**Comment by felixmariotto** [comment]
@swingingtom I'm not with my computer just now so I can't try, but I think there is an issue [here](https://github.com/felixmariotto/three-mesh-ui/blob/efef7ade87d4cdfd1439ecc5678e15817c0964f0/src/components/core/MeshUIComponent.js#L45)
It's been long I wrote this so I may be wrong, but I think it should be like this :
`if ( this.parent.isBlock && this.parent.getHiddenOverflow() )`

**Comment by swingingtom** [comment]
This is indeed confirming why we can't act directly on Text. 
But I cannot determine if this will be trivial to fix

**Comment by swingingtom** [comment]
We couldimagine redoing a more advanced overflowHidden example, that would contains many different parenting structures in order to be sure we don't have regression while fixing this one.

**Comment by hschwane** [comment]
ran into this today as well while trying to clip on a block containing text directly. As this is closed, I assume it will not be changed / fixed?
I would suggest to add a warning to the docs then, that it only works with an additional in-between block.
