### ISSUE TITLE
unused src property

### ISSUE THREAD

**Issue by swingingtom** [felixmariotto/three-mesh-ui#156]
The only reference the src attribute is in a switch/case of MeshUIComponent.
There is no documentation about it.
Could it be remove?

**Comment by felixmariotto** [comment]
My bad yes, I forgot about this one... I think it's an attribute I added while adding the background image feature, before to go for `backgroundTexture`

**Comment by swingingtom** [comment]
Ok so this seems safe to clean it.

By the way, this is like the only unused part of code I found 👍
