### ISSUE TITLE
Disabling word-wrap

### ISSUE THREAD

**Issue by marwie** [felixmariotto/three-mesh-ui#166]
Hello, 

is there an option to disable horizontal wrapping for text?

**Comment by swingingtom** [comment]
Hello @marwie Not that Im aware of. 
You could make a large Block, then a Text inside it and only use "\n" when you want to break line

**Comment by marwie** [comment]
Thanks for answering. Then: Is there an api way to precalculate the resulting text size in a block/text element? E.g. get height per line and total width of all characters?

**Comment by swingingtom** [comment]
There is first step in that direction, but no.
What are you trying to achieve ?

**Comment by marwie** [comment]
I'm exporting UI from Unity to threejs. The text component has overflow options that would be nice to support as well but for that to work I would need to calculate some mesh sizes myself (I think) or have three-mesh-ui handle it automatically.

Unity:
![image](https://user-images.githubusercontent.com/5083203/157411022-b04c7de1-cd3b-437b-aa06-bd517887a239.png)

threejs:
![image](https://user-images.githubusercontent.com/5083203/157411069-11b97ae0-1217-4e77-b54e-f179d8f6fe5a.png)

**Comment by swingingtom** [comment]
Ok, I think this should be possible with not much changes. Be right back

**Comment by swingingtom** [comment]
@marwie you can find a workaround here on that [forked branch](https://github.com/swingingtom/three-mesh-ui/tree/feature/export-lines-demo-single-line), the basic setup example shows how to workaround

It requires a core change, which Im going to PR here. The change allow a BoxComponent to be able retrieve its lines properties. 

Then using those lines to sum all their width 
```javascript
container.onAfterUpdate = function(){

		if( container.lines.length > 1 ){

			// add the width of all lines
			let newWidth = container.lines.reduce( (accu, line) => { return accu + line.width }, 0);

			// also add one space per line ( to handle additional space when both lines would be end-to-end )
			// Ideally instead of container.getFontSize(), the space character size should be used
			// Also, this can cause issue when container is really thin, because each char will be a line, then add space
			//newWidth += (container.lines.length-1) * container.getFontSize();
			// or
			// use a constant compensator
			newWidth += container.getFontSize() * 3;

			// also apply its padding
			newWidth += ( container.padding * 2 || 0 );


			setTimeout( ()=>{

				// then update the container size
				container.set({width:newWidth});

				// the set timeout is useless, just to show the 2 passes

			}, 1000 )


		}
	}
```

**Comment by JoeCoppola-HIA** [comment]
It would be nice to have a feature to disable word wrap and use the best fit functionality in tandem to have a line of text that will scale as it gets shorter or longer.

**Comment by swingingtom** [comment]
I share the same opinion, but im not sure how the api should be.

-  `word-wrap` to `none` ? 
- `multiline` to `false` ?

We also had discussion about width auto...

**Comment by swingingtom** [comment]
@marwie on the latest version 6.3.2, `.lines` property is now available

**Comment by marwie** [comment]
Wow fantastic news! Thanks I'll try that later

**Comment by swingingtom** [comment]
@JoeCoppola-HIA It depends what we expect for `word-wrap:false` alone.

In my opinion, it might be too much implicit for automatically resizing the container.

**Comment by marwie** [comment]
hello @swingingtom could you have a look at this fiddle, it looks like the timeout is not useless - without it it doesnt always work and sometimes has the wrong width. See https://jsfiddle.net/we3pvs76/ and try clicking "Run" multiple times

https://user-images.githubusercontent.com/5083203/157964373-4c5da975-ced6-4c9b-9f41-ffa3291cd44a.mp4

**Comment by swingingtom** [comment]
@marwie indeed... And Im pretty sure I already nailed it down. In the meanwhile if you need a workaround you could wrap the set to be executed next frame

```javascript
    requestAnimationFrame(() => {
        container.set({ width: newWidth });
    });
```

**Comment by marwie** [comment]
My workaround right now is just to timeout 1 ms - as I only need to do this once for now it is alright (it is a visible flicker for one frame but that's for now)

**Comment by swingingtom** [comment]
I was a bit skeptical but finally nailed it. PR is coming.

But in the current workaround you'll still need to get rid of the flick frame by yourself. You could set the visible of the text to false until more than one line...

**Comment by marwie** [comment]
Great good to hear!

**Comment by swingingtom** [comment]
__v6.4.0+__ has now more `whitespace` values. 

See [whitespace example](https://felixmariotto.github.io/three-mesh-ui/#whitespace) and [whitespace documentation](https://felixmariotto.github.io/three-mesh-ui/#whitespace)    

In your case, it won't solve the fact that the container should still be resized
