### ISSUE TITLE
Kerning

### ISSUE THREAD

**Issue by lojjic** [felixmariotto/three-mesh-ui#17]
I've noticed that neither of the text implementations honor kerning offsets for glyph pairs. I'm not sure if the current font encoding carries kerning information, but if it does then honoring that would be a significant improvement.

**Comment by felixmariotto** [comment]
Thanks for pointing this out, it should be supported at some point.

**Comment by trusktr** [comment]
Troika's `TextMesh` supports this. Worth looking into. @lojjic Would you be willing to try importing that here and hooking it in?

**Comment by felixmariotto** [comment]
It's not worth creating a dependency just for supporting kerning.   

Some hints to support it : 

- This should have 'leftAnchor' and 'rightAnchor' parameters
https://github.com/felixmariotto/three-mesh-ui/blob/d7d9b70748340965dbba6fa68ec0cecca27935ad/src/components/Text.js#L110-L117

- Somewhere here these two parameters should be looked up for computing `inline.offsetX`
https://github.com/felixmariotto/three-mesh-ui/blob/d7d9b70748340965dbba6fa68ec0cecca27935ad/src/components/core/InlineManager.js#L37-L90

**/!\ There may be issues with the computed lines length, it must be checked.**

- InlineBlock could produce 'leftAnchor' and 'rightAnchor' of 0 here, but a more elegant solution would be to default to 0 when these parameters are not found in InlineManager.
https://github.com/felixmariotto/three-mesh-ui/blob/d7d9b70748340965dbba6fa68ec0cecca27935ad/src/components/InlineBlock.js#L72-L77

- To get glyphs kerning, look into `charOBJ` parameters in `GetGlyphDimension`, it follow [these specs](http://www.angelcode.com/products/bmfont/doc/render_text.html)
https://github.com/felixmariotto/three-mesh-ui/blob/d7d9b70748340965dbba6fa68ec0cecca27935ad/src/components/core/TextManager.js#L48

**Comment by swingingtom** [comment]
If noone started it yet, I would like to give a try at this implementation

**Comment by felixmariotto** [comment]
@swingingtom go ahead !

**Comment by felixmariotto** [comment]
adressed by #106
