### ISSUE TITLE
remove block offset 

### ISSUE THREAD

**Issue by eviltik** [felixmariotto/three-mesh-ui#171]
From https://discourse.threejs.org/t/three-mesh-ui-vr-ui-user-interface/14863/6

[@gkjohnson](https://discourse.threejs.org/u/gkjohnson) said

> I see that there’s a 0.01 unit offset being applied for every level of nesting in nested block. Is this to avoid z-fighting
> when rendering two planes that render to depth? Have you considered using Material.polygonOffset for this? 
> That should allow you to keep all layers on a single plane if the user desires.

You (felix) replied

> I know Material.polygonOffset but so far I’ve made the choice of letting the users create their own materials. 
> I think I could set polygonOffset parameters to the materials they pass, but I’m not very fan of doing this, 
> I think people expect the material they pass to be used as-is. However I’m realizing that working with users 
> materials is a huge limitation for my lib, and there will probably be an update shortly, so that the user can 
> pass parameters to apply to a library-created material. At this point the default offset will be 0, and materials 
> will have polygonOffset default values set to avoid z-fighting. I think users should still have the possibility of 
> using a custom material though.

My question:

How do i keep all layers on a single plane ? :)  
If it's not possible without having z fighting, with the current version, what should be done in the code to test it ?

Thank you !

**Comment by swingingtom** [comment]
hello @eviltik 

I might be wrong, but I guess you simply have to **explicitely** set the offset property to zero ?
```javascript
const text = new ThreeMeshUI.Text({offset:0,content:"Text without offset"});
```

by default this value is set to **0.01** if not defined

**Comment by swingingtom** [comment]
> How do i keep all layers on a single plane ? :)
If it's not possible without having z fighting, with the current version, what should be done in the code to test it ?

You could explicitely set `renderOrder` after texts are built
```javascript
const text = new ThreeMeshUI.Text({offset:0,content:"Text without offset"});
text.onAfterUpdate = function()
{
    if( text.children.length > 0 )
    {
        text.children[0].renderOrder = 1;
    }
}
````

**Comment by eviltik** [comment]
Got it, test time ! thank you
