### ISSUE TITLE
Consider using HTTPS for WebXR

### ISSUE THREAD

**Issue by eviltik** [felixmariotto/three-mesh-ui#172]
`npm start` open http://localhost:8080/ 

But i can't access it using my headset VR immediatly.

We need to listen to a private IP addr too, rather than localhost. This make **HTTPS is mandatory for WebXR.**.

TODOs

## Packages check
* [ ]  Check webpack/webpack-dev version need to be upgraded, and if yes, understand impacts of upgrade / test.

##  Package.json changes
* [ ]  Add a new script  entry 
```
"start-https": "webpack-dev-server --config config/webpack.httpsConfig.js --open --env.NODE_ENV=dev",
```

### SSL Certificates automatic generation
* [ ]  Create a home dir ( /home/user/.threemeshui )
* [ ]  Try to read certificates (async)
* [ ]  If not exists, create self signed certificate (key+crt, async)

### SSL Certificates should be provided to webpack-dev-server
* [ ]  Adjust webpack-dev-server option for https

### Network & system
* [ ] Search for and use first private wifi or network ip address (i.e 192.168, 10.34, 172.16, ...) rather than localhost, async
* [ ] and/or use static ip addr set in webpack.httpsConfig.js

## README
* [ ] Speak about `npm run start-https`, why, for who
* [ ] Speak about the Security alert in the browser when first access to the webpage, due to "self signed" certificates. and what to do (i.e accept & continue)

**Comment by felixmariotto** [comment]
It's possible to run the test pages locally using your VR headset, that's how this package was built from the ground up (works on my Quest anyway).

Steps:
1) download Android Debug Bridge SDK [here](https://developer.android.com/studio/releases/platform-tools).
2) connect your HMD via USB and power it up.
3) open command prompt, navigate to the downloaded SDK folder.
4) run `adb devices`. You should see your HMD listed in the console: <img width="271" alt="Screenshot 2022-03-22 213855" src="https://user-images.githubusercontent.com/46470486/159572051-df7b4153-d2e4-4e22-8697-412185f36b4a.png">
5) run `adb reverse tcp:8080 tcp:8080` to enable port forwarding with the connectedd HMD.
6) in three-mesh-ui folder, run `npm start`.
7) access three-mesh test pages from your HMD at `http://localhost:8080`.

If this doesn't work for you, feel free to reopen.

**Comment by eviltik** [comment]
Yep, but you need to install and setup ADB, which require 3 more steps than a simple npm run command.

Not interested by a PR ? 

I should have to create a discussion rather than a ticket.

**Comment by felixmariotto** [comment]
Sorry I didn't mean to sound harsh, but all updates to the code involve work for the maintainers and could potentially introduce bugs. So if the update's only purpose is to add a nice to have development feature to address a need that is already addressed otherwise, in my opinion it's a waste of our limited resources... There are already a lot of tickets open marked with roadmap, feature request and 7.x.x tags, these things are our priority at the moment and I'm sure @swingingtom will appreciate your help if you wish to contribute.

**Comment by eviltik** [comment]
I can understand it's ok. I will contribute every where i can.

But i'll not use ADB, i don't have it, i don't wanna install it and i don't want to use it. I just want npm startssl or something like that and that's up and running without adb or liveserver or ..

FI, i'll code this change on my side only. It's only 1 npm package (pem) to add as a dev dep, things are already coded here https://github.com/eviltik/devsrv/blob/main/src/ssl.js just need to go deeper in webpack.

**Comment by eviltik** [comment]
Finaly, webpack dev server already support self signed certificate auto generation
https://github.com/eviltik/three-mesh-ui/commit/af46dbeab99c09956edf0857f285432a00abf9bc
