### ISSUE TITLE
Handling (or ignoring) characters that are not present in the font

### ISSUE THREAD

**Issue by aitchpea** [felixmariotto/three-mesh-ui#173]
In my example application I downloaded some text from an external source and then displayed it in a Text object - but this breaks as the text included characters that were not present in the font (which is just Roboto-msdf for background info).

It hit this error (in class MSDFGlyph constructor)
![image](https://user-images.githubusercontent.com/83715131/159512860-0d543335-8242-4c82-8e57-0fe03fe13b71.png)

which is quite reasonable - i.e. it cannot display it. 

What I am happy to do is to remove all characters that are not available - but cannot see which set of calls to make to do this. For example how would I programmatically get from a Text or Block (or whatever) to a font object where I could then check every character in my source string - as clearly removing the characters is easy once I know which ones are not displayable.

**Comment by swingingtom** [comment]
Hello @aitchpea 

you can access the font from the component _when font is loaded and ready_
```javascript
 const text = new ThreeMeshUI.Text({
    content: "ui ".repeat(8)
  });
  container.add(text);

  text.onAfterUpdate = function () {
    const font = text.getFontFamily();
    console.log(font.info.charset);
  };
```

Note that this should be ease upon 7.x.x when font class will be available ;)
