### ISSUE TITLE
6.3.2 version missing

### ISSUE THREAD

**Issue by user080975** [felixmariotto/three-mesh-ui#179]
Hi,

For some reason the latest version 6.3.2 isn't available via unpkg. For example this link returns a not found error:
https://unpkg.com/three-mesh-ui@6.3.2/dist/three-mesh-ui.js

Can you please update this link?

Thank You!

**Comment by swingingtom** [comment]
Hey @user080975, [readme has been updated](https://github.com/felixmariotto/three-mesh-ui#import) and you could find a new js build on v6.4.1

- js unminified https://unpkg.com/three-mesh-ui@6.4.1/build/three-mesh-ui.js
- js minified https://unpkg.com/three-mesh-ui@6.4.1/build/three-mesh-ui.min.js
- module unminified https://unpkg.com/three-mesh-ui@6.4.1/build/three-mesh-ui.module.js
- module minified https://unpkg.com/three-mesh-ui@6.4.1/build/three-mesh-ui.module.min.js

and also codesanboxes 
- [module build from npm package](https://codesandbox.io/s/npm-package-demo-2onzpo)
- [module buil within script tags](https://codesandbox.io/s/module-build-demo-bkmfi8?file=/index.html:281-913)
- [js build within script tags](https://codesandbox.io/s/js-build-demo-061eku)

Please note that the folder has changed     
__was__  .../three-mesh-ui@6.3.0/__dist__/three-mesh-ui.js    
__is__ .../three-mesh-ui@6.4.1/__build__/three-mesh-ui.js
