### ISSUE TITLE
I found that the parameters of the Block's bestFit property do not match those in the documentation

### ISSUE THREAD

**Issue by TNTsama11** [felixmariotto/three-mesh-ui#195]
[bestFit documentation](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#bestfit-v601) 
The argument in the document is 'none' 'shrink' 'grow' 'both'.
It doesn't work when I use 'both'.
The argument in the [InlineManager.js](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/InlineManager.js) is  'grow' 'shrink' 'auto' .
It work when I use 'auto'. -_-||
I hope you can fix this document .

**Comment by swingingtom** [comment]
Hello @TNTsama11 ,
Thank you for reporting it 👍 

The documentation has been update
