### ISSUE TITLE
(7.x.x) - [HELP] - Refine frame border shader

### ISSUE THREAD

**Issue by swingingtom** [felixmariotto/three-mesh-ui#199]
While spliting frame shader into chunks, I noticed some limitations. 
I tried my best to refine it by myself, unfortunately with no complete success.

### Border radius
1. Border radius is currently in world space values. Not sure this is a real issue, but changing the size of the block also change the radiused shape. Defining border radius related to uv[0-1] could allow to change the size of a block without changing its appearance. [See it here on codesandbox](https://codesandbox.io/s/not-relative-border-radius-hpxqop?file=/index.html)

2. Border radius are computed from four squares grid, each square having the uv[0.5,0.5] as center. This lead to some issues when the center of the defined radius should be greater than[0.5,0.5]. [See it here on codesandbox](https://codesandbox.io/s/border-radius-from-0-5-0-5-gdnh7k?file=/index.html)

### Border width
1. As I will soon start interactive components, I would like the ability to define border width per side (top-right-bottom-left)

### Current state
I started a branch with the current progress https://github.com/felixmariotto/three-mesh-ui/tree/7.x.x-feature/refine-frame-borders

Border radius seems mostly ok ( miss smoothstep ) but borders aren't
![Screenshot_11](https://user-images.githubusercontent.com/17314210/166432475-3b1d8499-6d86-40a3-b84b-a8ab71ca26c7.png)

@felixmariotto @Enijar I can see that you worked on that part, if you could help me on this it would be great. Even just by commenting those parts would help me to understand how it works.
```javascript
float getEdgeDist() {
        // get the uv in [-1,1] referencial system
	vec2 ndc = vec2( vUv.x * 2.0 - 1.0, vUv.y * 2.0 - 1.0 );

        // get the ndc in world space coordinate
	vec2 planeSpaceCoord = vec2( u_size.x * 0.5 * ndc.x, u_size.y * 0.5 * ndc.y );

        // as from here, im lost...
	vec2 corner = u_size * 0.5;
	vec2 offsetCorner = corner - abs( planeSpaceCoord );
	float innerRadDist = min( offsetCorner.x, offsetCorner.y ) * -1.0;
	if (vUv.x < 0.5 && vUv.y >= 0.5) {
		float roundedDist = length( max( abs( planeSpaceCoord ) - u_size * 0.5 + u_borderRadiusTopLeft, 0.0 ) ) - u_borderRadiusTopLeft;
		float s = step( innerRadDist * -1.0, u_borderRadiusTopLeft );
		return mix( innerRadDist, roundedDist, s );
	}
}
```

**Comment by Enijar** [comment]
`corner` is simply half the `u_size` vector (x and y), `offsetCorner` is the amount of space available for the corner radius, and `innerRadDist` is the distance of the corner radius from the centre of the plane.

```glsl
vec2 corner = u_size * 0.5;
vec2 offsetCorner = corner - abs( planeSpaceCoord );
float innerRadDist = min( offsetCorner.x, offsetCorner.y ) * -1.0;
```

These four `if` checks correspond to the four corners of the plane, like in CSS: top left, then top right, then bottom right, and finally bottom left.

```glsl
if (vUv.x < 0.5 && vUv.y >= 0.5) {
    float roundedDist = length( max( abs( planeSpaceCoord ) - u_size * 0.5 + u_borderRadiusTopLeft, 0.0 ) ) - u_borderRadiusTopLeft;
    float s = step( innerRadDist * -1.0, u_borderRadiusTopLeft );
    return mix( innerRadDist, roundedDist, s );
}
if (vUv.x >= 0.5 && vUv.y >= 0.5) {
    float roundedDist = length( max( abs( planeSpaceCoord ) - u_size * 0.5 + u_borderRadiusTopRight, 0.0 ) ) - u_borderRadiusTopRight;
    float s = step( innerRadDist * -1.0, u_borderRadiusTopRight );
    return mix( innerRadDist, roundedDist, s );
}
if (vUv.x >= 0.5 && vUv.y < 0.5) {
    float roundedDist = length( max( abs( planeSpaceCoord ) - u_size * 0.5 + u_borderRadiusBottomRight, 0.0 ) ) - u_borderRadiusBottomRight;
    float s = step( innerRadDist * -1.0, u_borderRadiusBottomRight );
    return mix( innerRadDist, roundedDist, s );
}
if (vUv.x < 0.5 && vUv.y < 0.5) {
    float roundedDist = length( max( abs( planeSpaceCoord ) - u_size * 0.5 + u_borderRadiusBottomLeft, 0.0 ) ) - u_borderRadiusBottomLeft;
    float s = step( innerRadDist * -1.0, u_borderRadiusBottomLeft );
    return mix( innerRadDist, roundedDist, s );
}
```

Is the main issue that having a border radius greater than the width or height of the plane causes it to break or look weird?

**Comment by swingingtom** [comment]
Hey @Enijar thanks for that prompt answer.

I realize that there is two questions in my post, and therefore Im going to split them. 
If you could help me on **"BorderWidth Sides Top-Right-Bottom-Left"** that would be **great** !
If the second question is too vague, or took you too much time to help me, that not that bad.

## BorderWidth Sides - Top Right Bottom Left
With the current shader code, I think I could go further on this by myself, but I lack the understanding of some parts of the shader. Here is a picture to schematize one dial (one plane, divided in 4 dials)
![shader-borders](https://user-images.githubusercontent.com/17314210/166469190-da6aa2a3-01cd-4374-ab56-55b8856c95f3.jpg)
I just can't understand how the red areas border are found. 
The blue one, are circular distance. 

I think I would be able to split borderWidth in four dimensions If I understand that part.
How would you do such a thing?

## Border Radiuses ( second question, less important )

> Is the main issue that having a border radius greater than the width or height of the plane causes it to break or look weird?

It is, and it doesn't even have to be bigger than the plane, but bigger than the dial.
In the picture below, the glitch comes from the fact that the radius have to be contained in a bigger dial than [0,1] - [0.5,0.5]

![radius-issue-05-05](https://user-images.githubusercontent.com/17314210/166470328-944edf26-58a9-4a42-b722-69527ab03c73.jpg)

This is something I somehow manage to succeed ( minus the smoothstep )
![minus-smoothstep](https://user-images.githubusercontent.com/17314210/166470433-265d6b43-5734-40ad-9e82-a063b7773aa6.jpg)

It defines 9 dials instead of 4, computed after a "mediation" between required radiuses
 
![somehow-succeed](https://user-images.githubusercontent.com/17314210/166470648-400ac876-5018-4f98-96c0-1b8220c882a3.jpg)
Currently it could lead to some overlaps, which could also become an issue.

But here again, I cannot conceive a way to found borders for red areas.
![dials-with-sides](https://user-images.githubusercontent.com/17314210/166470786-e71f6b41-30ea-4a48-9da0-9f9d495b6609.jpg)

**Comment by Enijar** [comment]
I'm have the latest version of the `7.x.x-feature/refine-frame-borders` branch open now. Where are you testing the UI, is it on the `.border-` section [here](http://localhost:8080/#api__border)?

**Comment by Enijar** [comment]
Ignore my last comment, I see it's [here](http://localhost:8080/#dev__frames)

**Comment by swingingtom** [comment]
I might have chosen a wrong way. Dont feel bad to say it.

**Comment by Enijar** [comment]
It's cool, I fully understand what you're trying to achieve now. I think it's going to be hard to implement but will be a very good feature. I will have a play and post my feedback here

**Comment by swingingtom** [comment]
Many Thanks!
Take your time, there is no hurry from my side.

As stated before the branch contains both border dimensions and radius dial expansion. Tasks could be isolated I needed.

**Comment by Enijar** [comment]
I'm working on an SDF version of the fragment shader for more control over the plane border segments:

https://codesandbox.io/s/silent-pond-cpmnn8?file=/src/shader/fragment.glsl

**Comment by Enijar** [comment]
@swingingtom below is a WIP fragment shader which will eventually split the plane (block) into grid segments (currently 2x2). Can you read the comments I've left and let me know if this is heading in the direction of what you want. This needs a lot more work to get to where you eventually want to be, but just want to check I'm heading in the right direction.

**Reference Image**

![Screenshot 2022-05-03 at 23 52 42](https://user-images.githubusercontent.com/5284715/166585918-abdb40c4-baa8-4c06-ada8-d96960c3b82c.png)

**WIP Implementation**

[Full CSB version](https://codesandbox.io/s/silent-pond-cpmnn8?file=/src/shader/fragment.glsl)

```glsl
varying vec2 vUv;

float roundedSDF(vec2 uv, vec2 center, float radius) {
  return length(max(abs(uv - center) - center + radius, 0.0)) - radius;
}

float roundedSDF(vec2 uv, vec2 center, vec4 radii) {
  // Top left quadrant
  if (uv.x <= 0.5 && uv.y >= 0.5) {
    return roundedSDF(uv, center, radii.x);
  }
  // Top right quadrant
  if (uv.x >= 0.5 && uv.y >= 0.5) {
    return roundedSDF(uv, center, radii.y);
  }
  // Bottom right quadrant
  if (uv.x >= 0.5 && uv.y <= 0.5) {
    return roundedSDF(uv, center, radii.z);
  }
  // Bottom left quadrant
  if (uv.x <= 0.5 && uv.y <= 0.5) {
    return roundedSDF(uv, center, radii.w);
  }
  return roundedSDF(uv, center, radii.x);
}

// References: 
// 1. https://stackoverflow.com/a/68233743/2413722

void main() {
  vec2 center = vec2(0.5, 0.5);

  vec3 backgroundColor = vec3(0.5, 0.5, 1.0);

  // Border colors
  vec3 borderColorTopLeft = vec3(1.0, 0.0, 0.0);
  vec3 borderColorTopRight = vec3(0.0, 1.0, 0.0);
  vec3 borderColorBottomRight = vec3(0.0, 0.0, 1.0);
  vec3 borderColorBottomLeft = vec3(0.5, 0.5, 0.5);

  // Border thickness
  vec4 thickness = vec4(0.05, 0.05, 0.05, 0.05);
  
  // Radius of the corners
  vec4 radii = vec4(0.5, 0.1, 0.5, 0.1);
  
  // Calculate distance to edge.
  float distance = roundedSDF(vUv, center, radii);
  
  // Smooth the result (antialiasing)
  // @todo Add smoothstep min and max values for antialiasing
  float alpha = 1.0 - smoothstep(0.0, 0.0, distance);
  
  // Return the resultant shape
  vec4 color = vec4(backgroundColor, alpha);

  // Corner quadrant checks
  // @todo Make arbitary grid size instead of the current 2x2 (4 corners)
  bool topLeft = vUv.x <= 0.5 && vUv.y >= 0.5;
  bool topRight = vUv.x >= 0.5 && vUv.y >= 0.5;
  bool bottomRight = vUv.x >= 0.5 && vUv.y <= 0.5;
  bool bottomLeft = vUv.x <= 0.5 && vUv.y <= 0.5;

  // Draw topLeft corner
  if (topLeft && distance > -thickness.x) {
    color = vec4(borderColorTopLeft, alpha);
  }

  // Draw topRight corner
  if (topRight && distance > -thickness.y) {
    color = vec4(borderColorTopRight, alpha);
  }

  // Draw bottomRight corner
  if (bottomRight && distance > -thickness.z) {
    color = vec4(borderColorBottomRight, alpha);
  }

  // Draw bottomLeft corner
  if (bottomLeft && distance > -thickness.w) {
    color = vec4(borderColorBottomLeft, alpha);
  }
  
  // Discard anything with 0.0 alpha so it becomes transparent
  if (alpha == 0.0) discard;

  // If no corner color was assigned, this defaults to backgroundColor
  gl_FragColor = color;
}
```

**Comment by swingingtom** [comment]
Thanks @Enijar, that looks really nice and clean. And it's pretty amazing how the code readable is 👍 

That's make me think, in order to have top-right-bottom-left width and color, instead of wip topleft-topright-bottomright-bottomleft ones, borders drawing may be in two passes? This would lead to have quadrants for alpha computing, then for two passes for border color and thickness?

_Theorically_
```javascript
  // a quadrant is a sum of two sides
  if (top && distance > -thickness.x) {
    color = borderColorTop;
  }
  if (left && distance > -thickness.w) {
    color = borderColorLeft;
  }
```
instead of
```javascript
// Draw topLeft corner
  if (topLeft && distance > -thickness.x) {
    color = borderColorTopLeft;
  }
```
Maybe you already think about it, or already discarded that idea?

Anyways, that a nice wip, and Im pretty sure that 7.x.x FrameShader would enjoy to host that code.

**Comment by Enijar** [comment]
The idea is to eventually have a 3x3 grid instead of the current 2x2 grid. The 3x3 grid would have the following border segments:

- Top left
- Top middle
- Top right
- Middle right
- Bottom right
- Bottom middle
- Bottom left
- Middle left

I will play with this some more tonight and add support for background and border opacity, then share the updated shader 👍

**Comment by swingingtom** [comment]
That would be amazing, thanks again for the help!

**Comment by swingingtom** [comment]
Done with #206 
@Enijar thanks for the help, you are still more than welcome to optimize shader or corner mediation
