### ISSUE TITLE
Express should be Dev Dependency?

### ISSUE THREAD

**Issue by gkjohnson** [felixmariotto/three-mesh-ui#2]
Hey! Awesome work. Glad to see someone working on nice 3d text layout!

One thing I noticed in the package.json is that express should probably be a dev dependency rather than a regular dependency, right?

Thanks again!

**Comment by felixmariotto** [comment]
Thanks for you support !

I saved express as a dependency because I deploy the examples page with Heroku, but after looking a bit more into it, I found that one can tell Heroku to skip pruning dev dependencies, so it's now in dev dependencies as you suggested. 👌
