### ISSUE TITLE
Querying 'natural' size of text from ThreeMeshUI.Text (for 6.x and what to expect for 7.x)

### ISSUE THREAD

**Issue by aitchpea** [felixmariotto/three-mesh-ui#207]
I have searched through the documentation / examples issues and have not found an answer to my question (but understand I might be incompetent and it is there already).

My ideal is to be able to query for the resulting calculated dimensions of the text i pass in (e.g. to ThreeMeshUI.Text) to optimise the Block dimensions I display it in - versus, right now all the examples I can see pass in a hardwired size of "width" + "height" to the Block.

in 6.x I can see that I can see ThreeMeshUI.Text.getFontFamily but there are no obvious ways of asking "if I gave the text 'xxx' or 'yyy' what is the resulting natural render size, taking into consideration the fontSize etc etc)".

I understand 7.x is going to have better font objects - so is the above question better suited to this branch (and is the branch stable enough so that people could use it? I am happy to work through issues if it is 'reasonably' stable)

Right now I am seeking to display lots of text objects throughout a VR environment and would prefer not to have fixed size blocks (i.e. all text must fit into width of 0.5) or pick arbitrary scales to proxy the likely rendered size of text

**Comment by swingingtom** [comment]
Hello @aitchpea    

## 6.x
This was previously answerd on #166 for v6.4. Here is a [codesandbox about it](https://codesandbox.io/s/natural-width-z5fy0u?file=/src/sandbox.js)    
The idea is to use `Block.onAfterUpdate` to retrieve the `.lines` property. 
This property will give a computed data of each text lines in the block.
```javascript
textContainer.onAfterUpdate = function () {
    //1 find the greaterWidth
    let width = 0;
    //2 increase the height
    let height = 0;
    for (let i = 0; i < container.lines.length; ++i) {
      if (container.lines[i].width > width) {
        width = container.lines[i].width;
      }

      height += container.lines[i].lineHeight;
    }

    // with  three-mesh-ui v6, only box-sizing:border-box is available
    // so you should also manually add padding to width & height
    width += 0.25;
    height += 0.25;

    // Then change a greater container to fit background
    container.set({ width, height });
  };
```
**Please note:** _This require `whiteSpace` to not be : 'normal' and therefore your text content should have line-breaks (\n)_

Hopefully, this is what you were looking for.

## 7.x
About 7.x.x, this kind of feature are meant to be provided as `Behaviors` without requiring users to onAfterUpdate it by themself. 
Whereas 7.x.x tends to mostly be stable, Behaviors api doesn't handle yet enough implementations to be qualified as stable.

If you want to dive into 7.x.x to implement this behavior, I would be happy to brief you,

**Comment by swingingtom** [comment]
@aitchpea did it helped ?

**Comment by aitchpea** [comment]
Firstly, it did exactly what I needed - so thank you for your fantastic help, it resized the items perfectly.
I didn't reply immediately as I wanted to see if there were any wrinkles in how it worked  but I could not see any (and then I incompetently forgot to send feedback..)
It would be great to get the above info into the online documentation - do you mind me sending PRs for tweaking the text or is there a formal process to follow?

Could you send some details behind the proposed Behaviors for 7.x so that I can read it (and if it makes sense I can then ping and see how to go about helping)

Thanks again (I shall close this issue out later today if I don't find anything else to add as you have answered all my questions)

**Comment by swingingtom** [comment]
Thanks for the feedback. I will reach you in order to provide more information about behaviors.

**Comment by swingingtom** [comment]
@aitchpea I created a chat page https://github.com/felixmariotto/three-mesh-ui/discussions/208 to share some informations about Behaviors
