### ISSUE TITLE
Cannot read properties of null (reading 'x')

### ISSUE THREAD

**Issue by bostondevin** [felixmariotto/three-mesh-ui#210]
I'm getting this error when I try and add it to a scene - it seems to be creating the Object3D fine, and I can add other things to the scene ok too - just when I try and add the Block it gives me this:

three.module.js:17366 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at SingleUniform.setValueV3f [as setValue] (three.module.js:17366:9)
    at WebGLUniforms.upload (three.module.js:18156:7)
    at setProgram (three.module.js:27991:18)
    at WebGLRenderer.renderBufferDirect (three.module.js:26943:19)
    at renderObject (three.module.js:27551:10)
    at renderObjects (three.module.js:27520:5)
    at renderScene (three.module.js:27444:40)
    at WebGLRenderer.render (three.module.js:27262:4)
    at RenderPass.render (RenderPass.js:61:12)
    at EffectComposer.render (EffectComposer.js:141:9)

```
import * as THREE from 'three';
const threeMeshUIModule = await import('three-mesh-ui');
ThreeMeshUI = threeMeshUIModule.default;

const forceGraphModule = await import('3d-force-graph');
ForceGraph3D = forceGraphModule.default;
Graph = ForceGraph3D()(container)

const testPanel = new ThreeMeshUI.Block({
	width: 1.2,
	height: 0.7,
	padding: 0.2,
	fontFamily: './assets/Roboto-msdf.json',
	fontTexture: './assets/Roboto-msdf.png'
}).add(new ThreeMeshUI.Text({
	content: 'Some text to be displayed'
}));

Graph.scene().add(testPanel);

```

**Comment by swingingtom** [comment]
Hey @bostondevin ,
It is difficult to help you only with this snippet. If you could build a codesandbox it will be easier, and I will be glad to assist you.

At first sight, I would tell you that `container` doesn't exist, but as you said you were able to add other things to the scene, I guess this snippet isn't complete, and `container` is not the issue

Did you add `ThreeMeshUI.update();` in the render loop ? 

Which version of three-mesh-ui are you using? For my own education, could you tell me what are the benefits or advantages of  `await import('three-mesh-ui)` ?
