### ISSUE TITLE
Use PlaneGeometry instead of PlaneBufferGeometry

### ISSUE THREAD

**Issue by kalegd** [felixmariotto/three-mesh-ui#226]
With [*BufferGeometry names being deprecated](https://github.com/mrdoob/three.js/pull/24352) and staged for removal in a later three.js release, we should switch PlaneBufferGeometry to PlaneGeometry in `/content/MSDFGlyph.js`

I understand there are major changes coming with the 7.x.x version, but if you're open to it I'd like to make a small pull request for the 6.x version in the meantime to rename this

**Comment by swingingtom** [comment]
Hello @kalegd ,
That would be great. Maybe we should also change the peer dependency requirement of three.

It is already done in 7.x.x.
Thanks

**Comment by kalegd** [comment]
Whoops forgot to close this issue. Thanks again for helping approve this so fast back then!
