### ISSUE TITLE
I get an error when I use Chinese

### ISSUE THREAD

**Issue by aile1997** [felixmariotto/three-mesh-ui#229]
I changed a json font library and still got an error
![image](https://user-images.githubusercontent.com/78535301/194745725-e1446a06-98b8-4fcd-af00-b11eb92bcb65.png)

**Comment by swingingtom** [comment]
Hello @aile1997 ,
If you can share a sandbox it will help. Thanks

**Comment by aile1997** [comment]
小红书留不了微信，需要网课加微信发1871314237

**Comment by aile1997** [comment]
https://codesandbox.io/s/react-three-mesh-ui-forked-88c6r4

**Comment by aile1997** [comment]
Do not change the json font. If the font is in Chinese, an error is reported.  After changing the font library, another error is reported ，Maybe my json file is wrong. May I ask what tool you used to convert the .ttf file

**Comment by swingingtom** [comment]
We usually use https://msdf-bmfont.donmccurdy.com/

But other tools such as command lines were already reported as being valid.

If you check the json file for the impacted character, can you notice some missing or invalid properties ?

**Comment by swingingtom** [comment]
@aile1997 What I can see with your sandbox is that json and png do not match. 

Json file doesn't look to be in msdf format. Png is png for Roboto, not for PangMenZhengDao.

If you go on this site https://msdf-bmfont.donmccurdy.com/ upload PangMenZhengDao ttf, and then write all the characters you will need, you will have both json and png matching the proper msdf format
