### ISSUE TITLE
Identical sub-expressions on both sides of operator '-'

### ISSUE THREAD

**Issue by oleomachado** [felixmariotto/three-mesh-ui#232]
Hi, I was reading the code and found this line on the InlineManager.js file

![image](https://user-images.githubusercontent.com/2807634/196084923-354d0fff-6bc8-42a0-81d4-03aabd95731c.png)

I believe this may be a bug or a not required operation.

**Comment by swingingtom** [comment]
@oleomachado good catch !

**Comment by swingingtom** [comment]
Fixed in v6.5.4 https://github.com/felixmariotto/three-mesh-ui/blob/b9c19e542e5234bc964a44c1e7aa4eeb16676757/src/components/core/InlineManager.js#L48
