### ISSUE TITLE
Three-mesh-ui is not displayed on mirroring camera

### ISSUE THREAD

**Issue by IJohnDean** [felixmariotto/three-mesh-ui#234]
Hi!
Faced with such a problem that if the cameras are transferred to Mirror (using scale.x), then the blocks are not displayed

No mirror
![image](https://user-images.githubusercontent.com/60685145/199166411-34cd4ff6-6791-4ad6-97c8-34fd6978de51.png)

Mirror
![image](https://user-images.githubusercontent.com/60685145/199166515-00f87649-f70f-44b0-a4d4-3ff44a17239d.png)

Scale camera if mirror
![image](https://user-images.githubusercontent.com/60685145/199166596-6c38cace-6c9a-4a19-af97-ace74fc482e1.png)

**Comment by swingingtom** [comment]
Hi @IJohnDean ,

Thats actually a common issue. When using plane and camera scale x -1, be sure its material is renderer backSide. Or DoubleSide if you need both sides.

Solution is already detailed here #233 and you got a sandbox too.
https://codesandbox.io/s/camera-scale-x-requires-doubleside-rl7ygf?file=/src/index.js

**Comment by IJohnDean** [comment]
Thanks for the quick response.
I didn't find any similar Issues by searching.
Successful development!
