### ISSUE TITLE
How to update text content every frame?

### ISSUE THREAD

**Issue by edhyah** [felixmariotto/three-mesh-ui#243]
Hello,

I currently have the following code.

I first set up my UI:
```
screen = new ThreeMeshUI.Block({
    width: 0.5,
    height: 0.5,
});
text = new ThreeMeshUI.Text({
    content: "null",
    fontSize: 0.05,
});
screen.add(text);
screen.name = 'screen';
scene.add(screen);
```

My render loop then sets new content for UI at every frame:
```
function render() {
    const value = ...
    text.set({ content: JSON.stringify(value) });
    ThreeMeshUI.update();
}
```

Unfortunately, the text doesn't seem to update every frame. How can I force ThreeMeshUI to update the text content every frame? I have tried using `screen.update( updateParsing, updateLayout, updateInner )` with all of the booleans set to true but that doesn't do anything either.

If I change the background opacity every frame though, it does change each frame. But the text content doesn't.

Note please ignore any optimization concerns - just developing a quick prototype that needs text to render every frame.

**Comment by eviltik** [comment]
It's working here. Ensure the text is really a string btw.
