### ISSUE TITLE
three-mesh-ui vs Dom Overlays

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [felixmariotto/three-mesh-ui#244]
Hi @felixmariotto,

Hope you are well! I appreciate your effort to create/maintain this library over the last 2 years.
I have used this library for a couple of WebXR VR projects and It had worked really well for me. 

I was wondering now that we have WebXR Dom Overlay support in VR browser's (Oculus) what are the different use cases where I would choose one over the other? 

Regards
Srinivas Prabhu

**Comment by swingingtom** [comment]
Hey @SrinivasPrabhu794,
I didn't find extensive examples of WebXR Dom Overlay but I guess the main point is that three-mesh-ui stays at 3D level and it is a 3D object. 

So I would go with : 
- Text behind or inside 3D world / object
- Shaders and Postprocessing

As I don't know much about WebXR Dom Overlay feel free to correct this if needed. Also Do you have other points I would have forget to compare both ?
