### ISSUE TITLE
sizing frames based on contained text

### ISSUE THREAD

**Issue by hschwane** [felixmariotto/three-mesh-ui#245]
When adding text to a block without providing any with or height properties, "Block got no dimension from its parameters or from children parameters" is printed to the console. Is it somehow possible to automatically size the block based on the text that is contained inside? 
So if this is not possible it would be a nice feature to have. It should be possible to calculate the text size based on the text, font and font size to make this possible.

**Comment by swingingtom** [comment]
Hey @hschwane 
7.x.x already provides 2 features : 
Width/Height auto : Children (even texts and inlines) defined width and height of parent 
Width/Height relative : (%) Children width/height can be set with relative value : percent of parent

**Comment by hschwane** [comment]
Thanks for the info. Seems like the new "auto" is what I am looking forward to. 
Will close this for now then.
