### ISSUE TITLE
Flickering/Overlapping effect in far containers

### ISSUE THREAD

**Issue by ponc83** [felixmariotto/three-mesh-ui#247]
Hi, firstly, thanks for this project.
I'm facing a problem when i set a container position quite far from the camera. You can reproduce it even in your jsfiddle
https://jsfiddle.net/felixmariotto/y81rf5t2/44/

If you set container position to ( 0, 0, -500 ), size to 500x500 and font size to 40 to make it visible, you will notice that the text renders bad, like it overlaps with the background.

![image](https://user-images.githubusercontent.com/29686284/211212428-05668b20-de01-40f4-ba0a-178f4669592a.png)

This other screenshot shows another strange thing
![image](https://user-images.githubusercontent.com/29686284/211212494-6259a034-6c87-4ac8-a4ca-312521afa11c.png)

The blue block is 100 unit distance from camera and it's shown well, the big black block is 500 unit far and present this bad behaviour i'm talking about. Also it seems like there is a pointlight that cut off the top text.

Any advice on how to solve this?

**Comment by swingingtom** [comment]
Hi @ponc83, 

Default values are set for rooms setup, having a 500 unit distance, might require increased values. 

This is especially the case for https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#offset property. It's default value of 0.02 may produces unexpexted behavior at such distance. Try to set offset to 1 or 2 or 10 to check if it solve your issue. 

Hopefully that’s it
