### ISSUE TITLE
scene.getObjectsByName not working

### ISSUE THREAD

**Issue by jmpedrosa** [felixmariotto/three-mesh-ui#248]
hi, threejs scene method getObjectByName is returning undefined, I realized that although I'm setting the name attribute, either in the block constructor or later on by calling someBlock.set({name:"someName"}) the attribute is not being set.

Is there any other way I could reference the objects on the scene whitout storing them appart?

Thank you for your time.

**Comment by swingingtom** [comment]
Hi @jmpedrosa,
On version 6.x.x `MeshUIComponent.set({});` only wrap its own properties. Whereas in 7.x.x it has a default handler that set its property.

In your case, simply go with : 
```javascript
const block = new ThreeMeshUI.Block({...});
block.name = "myblock";
//[...]
const blockByName = scene.getObjectByName("myblock");
```

Here is a sandbox sample : https://codesandbox.io/s/name-property-7vn09m?file=/src/sandbox.js
