### ISSUE TITLE
Support justifyContent: 'space-between' and 'space-evenly'

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/three-mesh-ui#25]
It should be possible to position Blocks similarly to [CSS justify-content](https://developer.mozilla.org/fr/docs/Web/CSS/justify-content) `space-between` and `space-evenly`.

It should be done by [BoxComponent](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/BoxComponent.js)

**Comment by swingingtom** [comment]
This kind of demo could be useful https://css-tricks.com/almanac/properties/j/justify-content/#aa-demo
With a trigger to set as direction : row/column.

We could also take this as an opportunity to deprecated left-right-top-bottom in favor of uniformized end-start
