### ISSUE TITLE
console logging output in latest version of three-mesh-ui (6.5.3)

### ISSUE THREAD

**Issue by m1r4c** [felixmariotto/three-mesh-ui#253]
Hello,

Let me begin with thanking you for this excellent library :)

I recently upgraded to the latest stable version 6.5.3 and started noticing a lot of console log output from this library, looks like there's an extra console.warn located here which probably should be removed?:
https://github.com/felixmariotto/three-mesh-ui/blob/24fd2b7760842a7fa67768a39762c5c491691ead/src/components/core/InlineManager.js#L264

An example of what we are seeing in console logs:
![image](https://user-images.githubusercontent.com/12200804/224950582-3ac9964b-554a-4bbb-a128-64be2c8e779e.png)

Best regards
Lars

**Comment by swingingtom** [comment]
Hi Lars,
Thank you for pointing this out.

**Comment by swingingtom** [comment]
fixed in v6.5.4
