### ISSUE TITLE
tests!

### ISSUE THREAD

**Issue by trusktr** [felixmariotto/three-mesh-ui#32]
Tests would be a great way to ensure nothing breaks. How do you feel about adding unit testing infrastructure?

**Comment by felixmariotto** [comment]
Ok, but what to test exactly ?   
I must admit I've never set up tests before, because I've always been the sole developer in my projects. I've not a single clue as to how to do this.   
Do you want to do it ?

**Comment by trusktr** [comment]
I can give it a stab. I have done it in various projects, so I can copy over a template. Then all we'd have to do for example is write files with `.test.js` like

```js
import Block from './Block'

describe('Block', () => {
  it('does this or that (make this description better of course)', () => {
    const b = new Block

    // do something with b

    expect(b.____).toBe(_____)
  })
})
```

**Comment by trusktr** [comment]
Once the lib gets bigger and more widely used, we'll be grateful we have the tests to catch regressions where changing one thing somehow breaks some other thing unexpectedly.

**Comment by felixmariotto** [comment]
> I can give it a stab.

Thank you !   
If you do it for just one or two features, then I will get the hang of it and complete it 👍

**Comment by trusktr** [comment]
Looking forward to circling back to this soon!

**Comment by eviltik** [comment]
Thinking about Puppeteer as an option for a high level tests.

* [ ] Check if [WebXR chrome addon](https://chrome.google.com/webstore/detail/webxr-api-emulator/mjddjgeghkdijejnciaefnkjmkafnnje?hl=fr) can be used with Puppeteer  (show stopper)
* [ ] npm run ui-test-prepare : browse examples, export screenshots as references
* [ ] npm run ui-test : browse examples, take screenshot, compare with references 

Because we can inject JS with Puppeteer, we can go really deep.

**Comment by swingingtom** [comment]
Hey @eviltik, I had a look at Puppeteer and was wondering how much we could do before going to snapshots.

Combining three data properties ( children, position, rotation, ... ) and three-mesh-ui data-properties ( lines, inlines ) we could already be able to perform a lot of tests preventing us from feature ( alignments, wordwrap, ... ) regressions. 

I made a proposal #193 and that would be great if someone could have a look and provide feedback or improvement. Cheers

**Comment by swingingtom** [comment]
@trusktr on the proposal I wasn't able to import. If you have a working template that allows import, that would be a better start.
