### ISSUE TITLE
Not compatible with latest create-react-app and Three.js

### ISSUE THREAD

**Issue by ghostandthemachine** [felixmariotto/three-mesh-ui#33]
Trying to get things installed and running but having issues. I am using the latest create-react-app and three.js via yarn. 

From yarn I get this error:

```
error three-mesh-ui@4.1.5: The engine "node" is incompatible with this module. Expected version "12.x". Got "14.2.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I can install with npm but the the dependency tree is broken.

**Comment by ghostandthemachine** [comment]
Didn't solve the actual issue but did get around this with:

`yarn add three-mesh-ui --ignore-engines`

This might have just been due to me being an npm/yarn novice so I'll close.

**Comment by felixmariotto** [comment]
It's not your fault, three-mesh-ui requested a bad node.js version in package.json : 

```javascript
"engines": {
    "node": "12.x"
 }
```

Since you have a higher version than 12.x, it refused to install... I just updated three-mesh-ui and publish to npm (version 4.1.6), now it takes any node.js version.   
Thanks for pointing this out !
