### ISSUE TITLE
Keyboard layouts cannot be reselected in example

### ISSUE THREAD

**Issue by gkjohnson** [felixmariotto/three-mesh-ui#35]
I just noticed this when clicking around the examples:

1. Load the [keyboard example](https://three-mesh-ui.herokuapp.com/#keyboard) page
2. Click "Nordic" to switch the layout
3. Click "English"
4. The layout cannot be switch back to English.
5. Click "German" to switch the layout
6. Click "Nordic"
7. The layout cannot be switch back to English.

This happens when trying to switch back to any layout that's already been selected.

I'm using mouse and keyboard on Windows in latest Chrome.

**Comment by felixmariotto** [comment]
Indeed.. It worked before, it must be a regression, I will check this. Thanks for the heads up  👍

**Comment by felixmariotto** [comment]
This is fixed with 4.2.2, thanks again.
