### ISSUE TITLE
Feature Request: Add support for custom text implementations

### ISSUE THREAD

**Issue by gkjohnson** [felixmariotto/three-mesh-ui#37]
I know you mentioned [here](https://github.com/felixmariotto/three-mesh-ui/issues/17#issuecomment-643743838) that you didn't want to add another dependency it might be worth considering support for custom or external text rendering systems. This might just mean documenting the text mesh interface that a class has to adhere to already and how fill it in but you'd know better!

My use case is to enable users to use a custom font from the web which would mean being able to parse a font and generate an SDF texture on the client. And unfortunately I'm not aware of any multi channel SDF texture generators in javascript. [Troika text](https://www.npmjs.com/package/troika-3d-text) would be an option to embed for this but using something like [Typr.js](https://github.com/photopea/Typr.js) or [Opentype.js](https://github.com/opentypejs/opentype.js) to parse fonts and generate an SDF for a custom solution would work too.

**Comment by felixmariotto** [comment]
Hi @gkjohnson,

I've documented here how to use custom fonts with three-mesh-ui : https://github.com/felixmariotto/three-mesh-ui/wiki/Creating-your-own-fonts

The current recommended workflow to use a custom font is to create it with donmaccurdy's MSDF generator : https://msdf-bmfont.donmccurdy.com/

It seems to be using this package internally, if you want your own generator : https://www.npmjs.com/package/msdf-bmfont-xml

 I can still document how to add a custom text type if you want, but I suspect the process will be longer for you than using the aforementioned package for generating multi-chanel SDF font files.

**Comment by gkjohnson** [comment]
I've seen how to generate new fonts with that app but unfortunately that requires generating them ahead of time. I would like to simplify the process for users and allow them to specify their own font without have to go through those hoops.

> It seems to be using this package internally, if you want your own generator : https://www.npmjs.com/package/msdf-bmfont-xml

I've seen that package but it's not compatible with web browsers so unfortunately it's not usable in this case. If you take a look at the source it just [calls out to some native executables](https://github.com/soimy/msdf-bmfont-xml/tree/master/bin) which are from [this msdfgen](https://github.com/Chlumsky/msdfgen) repo.

> I can still document how to add a custom text type if you want

That would be great!

**Comment by felixmariotto** [comment]
I've written this article to help you out : 
https://github.com/felixmariotto/three-mesh-ui/wiki/Using-a-custom-text-type
Let me know if it's unclear on certain points, I'll happily update it.

**Comment by gkjohnson** [comment]
Thanks @felixmariotto! When I get a chance I'll give it a go and submit a new issue if I run into any problems.

**Comment by swingingtom** [comment]
Hey @gkjohnson ,
Im wondering if you (or anyone else) had a chance to implement a custom text type?

Im on my way of 7.x.x and I would really really help to have a custom type text implemented to ensure the further implementation. 

Thanks!
