### ISSUE TITLE
ui is invisible

### ISSUE THREAD

**Issue by rscv5** [felixmariotto/three-mesh-ui#39]
my english is poor,so i try my best to describe the problem i meet. i hope you can get it.
i download the 'three-mesh-ui' code on github, and i create a three-mesh-ui panel in my html file by the guide, and there is no wrong in console.but the panel is invisible,only 'room' is visible. i don't know how to solve it, could you have any advise?thank you so much
there is my initContainer code

```javascript
var container;
function initContainer() {

	container = new ThreeMeshUI.Block({
		height: 1.5,
		width:1
	});

	container.position.set( 0, 1, -1.8);
	container.rotation.x = - 0.55;
	scene.add( container );
}
```

here is my init code
```javascript
function init() {

	initScene();
	initLight();
	initCamera();
	initRender();
	initControls();
	initContainer();   //here i init container
	const room = new THREE.LineSegments(
			new BoxLineGeometry( 6, 6, 6, 10, 10, 10 ).translate( 0, 3, 0 ),
			new THREE.LineBasicMaterial( { color: 0x808080 } )
	);
	scene.add(room);
	renderer.setAnimationLoop( loop );
}
```

only could see the room
![no](https://user-images.githubusercontent.com/55484220/87372884-33647800-c5bb-11ea-8465-83773bf5c5c4.png)

**Comment by rscv5** [comment]
another question is that: if i import FontJSON or FontImage like that:
                       `import FontJSON from "./fonts/Roboto-msdf.json";
			import FontImage from "./fonts/Roboto-msdf.png";`
there is an error like that:
![err](https://user-images.githubusercontent.com/55484220/87373269-f6e54c00-c5bb-11ea-8d69-2ba85b100d33.png)
/(ㄒoㄒ)/~~

**Comment by felixmariotto** [comment]
Hi, thanks for using three-mesh-ui.

About your first issue, do you call `ThreeMeshUI.update()` in your loop ?   
Three-mesh-ui needs this function call to know when to render something, otherwise it would update everytime a new component is added to the hierarchy, and this would lead to a tremendous performance drop.

**Comment by felixmariotto** [comment]
About the second issue, I'm not sure it's on three-mesh-ui, it rather looks like you misspelled the url, or maybe an issue with you bundler setup ? It would help to see your repo for this one.

**Comment by rscv5** [comment]
> Hi, thanks for using three-mesh-ui.
> 
> About your first issue, do you call `ThreeMeshUI.update()` in your loop ?
> Three-mesh-ui needs this function call to know when to render something, otherwise it would update everytime a new component is added to the hierarchy, and this would lead to a tremendous performance drop.

thank you so much, i truely call ' ThreeMeshUI.updata()'in my loop,and my loop code is that:
                  `function loop() {
				ThreeMeshUI.update();
				controls.update();
				renderer.render( scene, camera );
			}`
but it's still invisible.do you need all my  code? thank you again. your work is wonderful, but i could't work it /(ㄒoㄒ)/~~

**Comment by rscv5** [comment]
> About the second issue, I'm not sure it's on three-mesh-ui, it rather looks like you misspelled the url, or maybe an issue with you bundler setup ? It would help to see your repository for this one.

hi,you‘re right. i misspelled the url, so i corrected it. now i meet another problem is that:
![err2](https://user-images.githubusercontent.com/55484220/87492740-d2ea3f00-c67d-11ea-9722-5712cfa86612.png)
i use it in my .html files, not .js files. is the reason that causing this err?

**Comment by felixmariotto** [comment]
> i use it in my .html files, not .js files. is the reason that causing this err?

Yes it is, I guess that the examples misled you... Sorry about that, I will update them.   

In three-mesh-ui files, all the files in the [examples](https://github.com/felixmariotto/three-mesh-ui/tree/master/examples) directory are bundled with Webpack before to be sent to [production](https://three-mesh-ui.herokuapp.com/#basic_setup). `import image from 'path/to/my/image.png'` is illegal in JavaScript, it's only needed and allowed by Webpack because it changes the location of the images when bundling.   

If you pasted the files in their final location you don't need this, remove 
```javascript
import FontJSON from "path/to/Roboto-msdf.json";
import FontImage from "path/to/Roboto-msdf.png";
```
and type the files url directly in the component option : 
```javascript
container = new ThreeMeshUI.Block({
	height: 1.5,
	width:1,
	fontFamily: "path/to/Roboto-msdf.json",
	fontTexture: "path/to/Roboto-msdf.png"
});
```

**Comment by felixmariotto** [comment]
I guess you can't see any panel yet because you had this error with the imported files, because I can't see anything wrong in your code beside this.   
Let me know 🙂

**Comment by rscv5** [comment]
> > i use it in my .html files, not .js files. is the reason that causing this err?
> 
> Yes it is, I guess that the examples misled you... Sorry about that, I will update them.
> 
> In three-mesh-ui files, all the files in the [examples](https://github.com/felixmariotto/three-mesh-ui/tree/master/examples) directory are bundled with Webpack before to be sent to [production](https://three-mesh-ui.herokuapp.com/#basic_setup). `import image from 'path/to/my/image.png'` is illegal in JavaScript, it's only needed and allowed by Webpack because it changes the location of the images when bundling.
> 
> If you pasted the files in their final location you don't need this, remove
> 
> ```js
> import FontJSON from "path/to/Roboto-msdf.json";
> import FontImage from "path/to/Roboto-msdf.png";
> ```
> 
> and type the files url directly in the component option :
> 
> ```js
> container = new ThreeMeshUI.Block({
> 	height: 1.5,
> 	width:1,
> 	fontFamily: "path/to/Roboto-msdf.json",
> 	fontTexture: "path/to/Roboto-msdf.png"
> });
> ```

thank you sososoososo much~ i get it~ and  your guess is right i can't see any panel yet
i died at the first step,/(ㄒoㄒ)/~~ but you give me confidence! your patience makes me try again and again!
thank you, and here is my all  code:
`<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewpoint"
		  content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
		<link type="text/css" rel="stylesheet" href="main.css">
		<title>Test</title>

	</head>
	<body>
		<div id="info">
			<a href="http://threejs.org" target="_blank" rel="noopener">Hello world</a> rscv5
		</div>
		<script src="../build/three.js"></script>
		<script src="./jsm/libs/ThreeBSP.js"></script>
		<script src="./jsm/controls/OrbitControls.js"></script>
		<script src="./js/controls/OrbitControls.js"></script>
		<script src="../build/three.module.js"></script>

		<script type="module">

			import { VRButton } from "./jsm/webxr/VRButton.js";
			import ThreeMeshUI from "./jsm/libs/three-mesh-ui.js";
			import { BoxLineGeometry } from "./jsm/geometries/BoxLineGeometry.js";

			
			var SCREEN_WIDTH = window.innerWidth, SCREEN_HEIGHT = window.innerHeight;
			var VIEW_ANGLE = 45, ASPECT = SCREEN_WIDTH / SCREEN_HEIGHT, NEAR = 0.1, FAR = 1000;

			//renderer
			var renderer;
			function initRender() {

				renderer = new THREE.WebGLRenderer( { antialias: true } );
				renderer.setSize( window.innerWidth, window.innerHeight );
				renderer.xr.enabled = true;
				document.body.appendChild( VRButton.createButton( renderer ) );
				container.appendChild( renderer.domElement );

			}

			var camera;
			function initCamera() {
				//camera
				camera = new THREE.PerspectiveCamera( VIEW_ANGLE, ASPECT, NEAR, FAR );
				camera.position.set(  - 1, - 5,  80 );
				camera.lookAt( new THREE.Vector3( 0, 0, 0 ) ); 
			}

			var scene;
			function initScene() {
				scene = new THREE.Scene();
				scene.background = new THREE.Color( 0x505050 );

			}

			var controls, delta;
			var clock = new THREE.Clock(); // 更新轨道控制器
			function initControls() {
				controls = new THREE.OrbitControls( camera, renderer.domElement );
				controls.target = new THREE.Vector3( 0, 0, 0 );
				controls.autoRotate = false; // 自动旋转开启
				controls.update();

			}



			init();
			animate();
			window.onresize = onWindowResize;


			function render() {
				delta = clock.getDelta();
				controls.update( delta );
				renderer.render( scene, camera );
			}


			function onWindowResize() {
				camera.aspect = ASPECT;
				camera.updateProjectionMatrix();
				renderer.setSize( SCREEN_WIDTH, SCREEN_HEIGHT );

			}


			var ambientLight, directionalLight;
			function initLight() {

				// Light

				ambientLight = new THREE.AmbientLight( 0xfffffff, 1 );
				scene.add( ambientLight );
				directionalLight = new THREE.DirectionalLight( 0xffffff, 0.5 );
				scene.add( directionalLight );

			}

			var container;
			function initContainer() {

				container = new ThreeMeshUI.Block({
					height: 1.5,
					width:1
				});

				container.position.set( 0, 1, -1.8);
				container.rotation.x = - 0.55;
				scene.add( container );
			}

			var container;
			function init() {

				container = document.createElement( 'div' );
				document.body.appendChild( container );
				initScene();
				initLight();
				initCamera();
				initRender();
				initControls();
				initContainer();
				const room = new THREE.LineSegments(
						new BoxLineGeometry( 6, 6, 6, 10, 10, 10 ).translate( 0, 3, 0 ),
						new THREE.LineBasicMaterial( { color: 0x808080 } )
				);
				scene.add(room);
				renderer.setAnimationLoop( loop );
			}

			function animate() {
				render();
				controls.update();
				requestAnimationFrame( animate );
			}

			function loop() {
				ThreeMeshUI.update();
				controls.update();
				renderer.render( scene, camera );
			}
		</script>
	</body>
</html>`
the result is that:
![re](https://user-images.githubusercontent.com/55484220/87513999-25daeb00-c6ac-11ea-90c4-cc1b03095e1c.png)
no panel, only room~~

**Comment by rscv5** [comment]
result update:
![re](https://user-images.githubusercontent.com/55484220/87514435-d1843b00-c6ac-11ea-8b51-31c92f13a830.png)

**Comment by felixmariotto** [comment]
![2020-07-15_092223](https://user-images.githubusercontent.com/46470486/87515868-caddcf80-c67c-11ea-8c1f-298d48b6242b.jpg)

This is weird, when I copy paste your code it works fine... Do you gave any error or warning in the console ?

**Comment by rscv5** [comment]
> ![2020-07-15_092223](https://user-images.githubusercontent.com/46470486/87515868-caddcf80-c67c-11ea-8c1f-298d48b6242b.jpg)
> 
> This is weird, when I copy paste your code it works fine... Do you have any error or warning in the console ?

wowowo~ it's so wonderful!!!! error? i did have.maybe it's the reason that cause invisible ? (((φ(◎ロ◎;)φ)))
like that:
![rrrrrr](https://user-images.githubusercontent.com/55484220/87516545-2b3a3480-c6b0-11ea-9b5a-66e2039ea988.png)
maybe i should change these files?

**Comment by felixmariotto** [comment]
The issue seem to be with how you import OrbitControls.

Something is wrong here : 

```javascript
<script src="./jsm/controls/OrbitControls.js"></script>
	<script src="./js/controls/OrbitControls.js"></script>
```

**Comment by felixmariotto** [comment]
I'm not home right now, as this is not really related to three-mesh-ui, you could ask on three.js forum ?

**Comment by felixmariotto** [comment]
Look how they import OrbitControls in this [this official example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf.html)

**Comment by rscv5** [comment]
> I'm not home right now, as this is not really related to three-mesh-ui, you could ask on three.js forum ?



> Look how they import OrbitControls in this [this official example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf.html)

thank you sosoooooososooso much~~~ it helps me very much~ i will try to solve it~~~wait for my good news~😀

**Comment by rscv5** [comment]
hi friend, emmmm, i imported OrbitControls officially, now i have no err or warning in my console, but there're still no panel(only room)~
(((φ(◎ロ◎;)φ)))
maybe it just can‘t work in my desktop? whatever thank you so much,your work is wonderful.

**Comment by felixmariotto** [comment]
Ok.. I'm closing this then, feel free to come back to me if you finally make it.
