### ISSUE TITLE
interactive_button.js example crash when pointer on button

### ISSUE THREAD

**Issue by yotamshacham** [felixmariotto/three-mesh-ui#41]
First of all, great work! The library looks very useful and hopefully it will keep growing!
Just wanted to report a crash when running the interactive button example:

VM420:1284 TypeError: Cannot read property 'point' of null
    at updateButtons (interactive_button.js?21ac:342)
    at loop (interactive_button.js?21ac:322)
    at onAnimationFrame (VM170 three.module.js:24520)
    at Object.onAnimationFrame [as callback] (VM170 three.module.js:15008)
    at XRSession$1.<computed>.onDeviceFrame (<anonymous>:1281:42)

Which is:

vrControl.setPointerAt( 0, intersect.point );

I'm running this in Chrome using the WebXR API Emulator, and the crash seems to be happening when the pointer is hitting the button, although its not consistent, i.e sometimes the button will highlight properly, sometimes it will crash.

**Comment by felixmariotto** [comment]
Sorry for the late response,

I forgot to check if `intersect` is truthy, I've udpated : 
https://github.com/felixmariotto/three-mesh-ui/blob/7f1846e1519c78ddf47a348332aca050fc5ae5ae/examples/interactive_button.js#L342

It should not crash anymore now, I'm closing, thanks a lot for reporting the issue. 👍
