### ISSUE TITLE
Creating complex layouts

### ISSUE THREAD

**Issue by corecode1** [felixmariotto/three-mesh-ui#46]
Hello! I've used this library for some time now, but still I didn't find a way to implement layout like one on this screenshot:
![text](https://user-images.githubusercontent.com/42890591/95595477-e0348100-0a54-11eb-90c6-482018f5de92.jpg)
The problem is, there's no way to set vertical spacing between paragraphs, like margin-top or something similar. There is interLine, but it affects every individual line. Adding several line breaks to text also has no effect, library treats them as single one. I could go with a separate block for every paragraph, but then I need to calculate size or bounds of generated text and modify block height to avoid overlapping. But for me, trying to compute it via bounding box gives wrong results. Of course, It could all be placed manually, but I need to create a lot of such screens with different text, and I can't define it in advance. So is there a way to do it, or am I missing something?

**Comment by felixmariotto** [comment]
Sorry for the late reply, I doubt you're still in need for a solution...
An easy way would be to add `/n` characters ( line breaks ), or if you want to control the spacing more precisely, interleave Text components with just a `/n` as their content, and set their `interLine` property.
