### ISSUE TITLE
Support for Web GL 2.0

### ISSUE THREAD

**Issue by daCking15** [felixmariotto/three-mesh-ui#47]
On iPhone Safari, three-mesh-ui only seems to work when Web GL 2.0 is disabled. I am on iOS 14.0.1. I will update to 14.2 and try again. If this issue persists, how can I go about making three-mesh-ui compatible with Web GL 2.0 in my project?

**Comment by daCking15** [comment]
Updating to iOS 14.2 did not fix the issue.

**Comment by felixmariotto** [comment]
Hi, it's possible that the few shaders of the libs are incompatible with webGL 2.0. I'm having a look at once, I will keep you posted.

**Comment by felixmariotto** [comment]
I forgot I actually checked that I made sure during three.js r117 → r118 migration that the shaders are compatible.
I'm afraid I don't quite know what's happening.

What do you mean exactly by _three-mesh-ui only seems to work when Web GL 2.0 is disabled_ ?
Does it crash altogether ? Do you have errors in your console ?
If not what is happening ? Nothing shows ?
Are you testing on your own projects, or on the [officials examples](https://three-mesh-ui.herokuapp.com/#basic_setup) ?

**Comment by daCking15** [comment]
When Web GL 2.0 is disabled, everything works as intended:![image](https://user-images.githubusercontent.com/15696956/99998350-8da4ef00-2d8c-11eb-815a-f3c2afd02e99.png)![image](https://user-images.githubusercontent.com/15696956/99998360-9269a300-2d8c-11eb-8638-15c81ae515a2.jpeg)

However, when Web GL 2.0 is enabled, the container does not show up:
![image](https://user-images.githubusercontent.com/15696956/99998422-a44b4600-2d8c-11eb-9e0b-26b1edca1b29.png)![image](https://user-images.githubusercontent.com/15696956/99998429-a7463680-2d8c-11eb-8ae2-3b1379a5b1e1.jpeg)

**Comment by daCking15** [comment]
I need to setup debugging on my iPhone before I can check for errors.

**Comment by felixmariotto** [comment]
Can you please do that ? I don't have an iPhone, so I can't check myself.
Three-mesh-ui supports WebGL 2.0 in Chrome...

**Comment by daCking15** [comment]
![image](https://user-images.githubusercontent.com/15696956/100011617-fa75b480-2d9f-11eb-91c0-89f5a081bb02.png)

**Comment by felixmariotto** [comment]
Please check this updated example : [https://three-mesh-ui-stage.herokuapp.com/#basic_setup](https://three-mesh-ui-stage.herokuapp.com/#basic_setup)
It's free hosting so it can take a few seconds to open.

**Comment by felixmariotto** [comment]
Tell me if it works, so I update the package on NPM

**Comment by daCking15** [comment]
Yes, it works in Web GL 2.0 now, thank you!

**Comment by felixmariotto** [comment]
Great ! I publish to NPM, it's version 4.4.3
