### ISSUE TITLE
Space error

### ISSUE THREAD

**Issue by gonnavis** [felixmariotto/three-mesh-ui#49]
Very simple [demo](https://raw.githack.com/gonnavis/three.js/three-mesh-ui/examples/three-mesh-ui_hellospaceworld.html) only contain character "Hello world" will fail:
```
three-mesh-ui.js:1 TypeError: Cannot read property 'width' of undefined
    at Object.getGlyphDimensions (three-mesh-ui.js:1)
    at f.getGlyphDimensions (three-mesh-ui.js:1)
    at three-mesh-ui.js:1
    at Array.map (<anonymous>)
    at f.parseParams (three-mesh-ui.js:1)
    at three-mesh-ui.js:1
    at new Promise (<anonymous>)
    at three-mesh-ui.js:1
    at new Promise (<anonymous>)
    at Function.callParsingUpdateOf (three-mesh-ui.js:1)
```
I found that the space in it caused this error.

A [complex demo](https://raw.githack.com/gonnavis/three.js/three-mesh-ui/examples/three-mesh-ui.html) without spaces works well.

**Comment by felixmariotto** [comment]
ok, that was because there is no letter `j` in your charset, and that was the character three-mesh-ui looked for when it didn't find a `width` property on a character. That was really too western-centric, sorry about that...

It's fixed in 4.4.5, now it doesn't need to look for any character
