### ISSUE TITLE
Idea: remove dist from the repo

### ISSUE THREAD

**Issue by trusktr** [felixmariotto/three-mesh-ui#5]
It is an annoyance for most people to have to see diffs that also include the `dist/` folder. Three.js includes the `build/` folder, but the vast majority of all JavaScript project don't do it.

We can build `dist/` for when we publish to NPM (or GitHub releases). People can get the built files from `unpkg.com`.

**Comment by trusktr** [comment]
Oh wait, it looks like `build/` is the build output folder. Normally, the most projects use `dist/` as the output folder (a convention in the JS community).

If `dist/` is not a built output folder, we can rename it to something else (not sure what yet), and `build/` can be renamed to `dist/` (but not committed to the repo).

**Comment by felixmariotto** [comment]
Yes I would like to ignore the dist folder when pushing to github, but on another hand I need my local git repo to update this folder because I push the app to heroku, this is the [examples page](https://three-mesh-ui.herokuapp.com/#basic_setup). I'm sure there is a way to do that cleanly, I will look into this.

> We can build dist/ for when we publish to NPM (or GitHub releases). People can get the built files from unpkg.com.

This sounds like the right solution, I want to make the bundled app available somehow, for those who include libraries with script tags.

**Comment by Zetaphor** [comment]
> This sounds like the right solution, I want to make the bundled app available somehow, for those who include libraries with script tags.

Github now has [actions and workflows](https://github.com/features/actions), you can easily automate builds and releases triggered by a tag push

**Comment by trusktr** [comment]
I love GitHub Actions. Super easy to set up CI, automated tests, etc!

**Comment by felixmariotto** [comment]
This has been done.   
Dist is not pushed in the repo anymore, but is still accessible from NPM, and from unpkg.   
I've added a section in the readme explaining the different import options.

**Comment by FredericBriolet** [comment]
Hi all, 

This library looks cool! However I'm afraid the build file is not accessible at all:

- when I run `npm install three-mesh-ui`, the `dist` folder doesn't exist in `node_modules/three-mesh-ui`.

- the unpkg link returns a 404:
[https://unpkg.com/three-mesh-ui@4.4.3/dist/three-mesh-ui.js](https://unpkg.com/three-mesh-ui@4.4.3/dist/three-mesh-ui.js)

**Comment by felixmariotto** [comment]
Sorry I messed up last time I published, the last patch fixes this : 
https://unpkg.com/three-mesh-ui@4.4.4/dist/three-mesh-ui.js

**Comment by FredericBriolet** [comment]
Hi @felixmariotto, thanks for the update, it works! Just for info in my case the CommonJS `require()` doesn't work the way it's written in the README.

This doesn't work, I get an empty object:
```
const ThreeMeshUI = require('three-mesh-ui/dist/three-mesh-ui.js');
console.log(ThreeMeshUI); // returns {}
```

This works:
```
require('three-mesh-ui/dist/three-mesh-ui.js');
console.log(ThreeMeshUI); // usable object
```

**Comment by felixmariotto** [comment]
@FredericBriolet thank you for pointing this !
I finally found a good piece of documentation for this, so now the lib is importable the following ways : 

`const ThreeMeshUI = require('three-mesh-ui')`

`import ThreeMeshUI from 'three-mesh-ui'`

`<script src='https://unpkg.com/three-mesh-ui'></script>`

I also updated the REAMDE
