### ISSUE TITLE
Content newlines

### ISSUE THREAD

**Issue by MartinSith** [felixmariotto/three-mesh-ui#51]
Hello.

I wanted to display text with some blank lines, but **Text** object with **Content** is ignoring more new-lines in a row.
For example text "_Hello\n\nThis is example text\n\nBye_" should have 3 text lines and 2 blank lines between them, but it only displays 3 text lines, each in a new line.

Is there a way to display blank lines using Text.content? 

Thanks,
Martin

**Comment by felixmariotto** [comment]
Hi @MartinSith,

It's something I didn't foresee, it should not be difficult to implement, let me have a look.

**Comment by felixmariotto** [comment]
Done ! Update three-mesh-ui to v4.4.9, it should work 👌
Let me know if you have any other issue.

**Comment by MartinSith** [comment]
Thank you very much for super quick reply and update.
It works just fine :)
