### ISSUE TITLE
Adding containers to camera

### ISSUE THREAD

**Issue by johansvenson** [felixmariotto/three-mesh-ui#61]
Hi, 

When adding containers as child to the camera rather than the scene i get the following errors (I want some of the ui oriented realtive to the view instead of stationariy in the word)

```
4three-mesh-ui:1` Block got no dimension from its parameters or from children parameters
updateLayout @ three-mesh-ui:1

8three-mesh-ui:1 'undefined' is an unknown value for the backgroundSize attribute
updateUVs @ three-mesh-ui:1

```
The gist of the code 

```
		scene.add(camera)
		camera.add(container);
		container.position.set(0,-0.35,-1);
		container.lookAt( camera.position );
```
Adding directly to scene works as expected

**Comment by felixmariotto** [comment]
Hi,

I don't understand, I tried to reproduce but I could not, here is a [fiddle](https://jsfiddle.net/felixmariotto/wqvyc4gf/11/).
Usually the errors you got a triggered when the root UI parent has no dimension, which makes it impossible to compute a layout.

**Comment by johansvenson** [comment]
Hi yep that was indeed the case. The problem was that the camera was cloned  - and that caused the problem...

**Comment by felixmariotto** [comment]
Oh I see ! I'm closing then
