### ISSUE TITLE
Text is invisible using orthographic camera

### ISSUE THREAD

**Issue by FMC64** [felixmariotto/three-mesh-ui#66]
Hello,

So I was trying to display some text using `THREE.OrthographicCamera`, but only the background is displayed and no text can be seen.
Reproducible example : https://jsfiddle.net/ds16nbgu/

![img_22](https://user-images.githubusercontent.com/43445534/115857176-a7c32600-a42d-11eb-9bfc-0bc4e7eb8c96.PNG)

I tried to play around with text shaders (vertex + fragment) : disabling clipping, setting `gl_FragColor` to `vec3(1.0)` but doesn't seem to help. I also tried to set `ThreeMeshUI.Text.frustumCulled` to `false` and `THREE.MeshBasicMaterial.depthTest` to `false`, without success.

I searched for a while and this doesn't seem to be a known issue. What might be the cause of that ?

Thanks by advance.

**Comment by felixmariotto** [comment]
Hi, thank you for reporting this, it's indeed an unknown issue...
I'm looking into this

**Comment by felixmariotto** [comment]
Apparently it's something to do with z-depth, and there is a quick fix, juste set the camera near frustum plane to a high negative value : [https://jsfiddle.net/felixmariotto/v4ns6mzg/34/](https://jsfiddle.net/felixmariotto/v4ns6mzg/34/)

However I'm still unsure why it happens, I'm still investigating.

**Comment by FMC64** [comment]
Awesome, playing with near / far planes did the trick for now !

It seems that using positive near plane value (0.1), camera needs to be at least 2.6 units away from origin in order to have the text displayed. https://jsfiddle.net/qv8zagLn/
I think the Z offset on text vertex shader (-0.005) makes the text go behind the near plane on orthographic camera with clipping planes being far away. We could be more aggressive with it and look for a minimal FP32 value that still prevents Z-fighting and avoids the text to get projected too far.

`0.00001` might be a way better candidate, even `0.000001` (looks a bit more risky tho).

Anyway thanks for the help !

**Comment by felixmariotto** [comment]
I just tried `0.00001` and it does fix the issue with the orthographic camera, so I will update this.
Thanks a lot for the report !

**Comment by FMC64** [comment]
My pleasure and thank you for your amazing job 🙏
