### ISSUE TITLE
How to modify Block's Frame three js render layer?

### ISSUE THREAD

**Issue by JoeCoppola-HIA** [felixmariotto/three-mesh-ui#70]
Hello, 

First let me say I am excited to be using this library! It's very impressive. 

In my project, I have two cameras rendering the scene, both responsible for rendering different objects in the scene and both very different in settings. To control what objects are rendered by what camera, I utilize Three JS's render layers. https://threejs.org/docs/#api/en/core/Layers

After creating a ThreeMeshUI Block object, I can set it's frame container's render layer to what I want, but that doesn't propagate down to the frame created in Block.js `updateLayout()` function. This results in the block always being rendered on layer 0. Is there any way I can set this frame's render layer after every time `updateLayout()` is called or should the creation of frame in `updateLayout()` also inherit the render layer of the frame container at the time of creation?

Thanks, 

Joe

**Comment by JoeCoppola-HIA** [comment]
One solution I just came up with was to access `frame` on my main update loop and modify it's render layer then. This ensures it's always set even if `updateLayout()` is called again.

**Comment by felixmariotto** [comment]
mh I see, it's a shame three.js won't apply layers ownership to children, you could just set the `Block` layer...
Well I suppose three-mesh-ui should be updated to support this use case then.

I think a versatile solution would be an optional callback `onAfterUpdate`, which would be called after every update : 
```javascript
myBlock.onAfterUpdate = function () {
  
  // do your manual update to myBlock.frame here

}
```

Note that this is better than updating `myBlock.frame` each frame in your main loop, because `myBlock.updateLayout` is called only if you set new [attributes](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#attributes) to `myBlock`, which usualy does not happen every frame ( for most use cases, it happens only once ).

Would this change help you ?

**Comment by JoeCoppola-HIA** [comment]
Thanks for the quick response. This would be a good change in my opinion! Makes the most sense and only adds functionality, shouldn't hinder.

**Comment by felixmariotto** [comment]
ok so starting from version 4.7.0, you can use `onAfterUpdate`, which is a callback called after any update on any component : 
```javascript
myBlock.onAfterUpdate = function () {
  
  this.frame // myBlock frame

}
```
I'm closing, but feel free to seek more help if needed.

**Comment by JoeCoppola-HIA** [comment]
Thanks a bunch!

**Comment by felixmariotto** [comment]
Just added an exemple for this functionality at https://three-mesh-ui.herokuapp.com/#onafterupdate

**Comment by JoeCoppola-HIA** [comment]
Just tested it on my end. Works as expected, gives me access after updates. I no longer need to check every update loop. Thanks for the quick update! Love the framework so far.

**Comment by JoeCoppola-HIA** [comment]
@felixmariotto, apologies for bothering you again, but do you know how I could use the same feature for Three Mesh UI Text? I noticed the Three Mesh UI Text object doesn't have a frame, rather it has a `textContent` property. Attempting to modify the layers on that does not result in it being rendered on the proper camera. Is there another three js object attached to a Three Mesh UI Text object that I should be modifying? 

Thanks again, 

Joe

**Comment by felixmariotto** [comment]
Hi !
Sorry I can't look into this just now, can it wait tomorrow ? Is Text failing to trigger onAfterUpdate, or is Text.textContent somehow not reacting to a change to its layer ?

**Comment by JoeCoppola-HIA** [comment]
Hey!

This for sure can wait until tomorrow, no worries there.

The text is indeed triggering onAfterUpdate, but if you set the `textContent` layers to anything other than Three's default render layer 0, it doesn't seem to react to the change. It's quite curious, as it seems like `textContent` is the actual Three JS object rendered, similar to the frame property on a Three Mesh UI block. To be safe, I tried setting the layers on both the Three Mesh UI Text object, as well as it's `textContent` property. No reaction though, text is still rendered on the default layer, layer 0. See the image below, hopefully it helps.

![Layers](https://user-images.githubusercontent.com/83366171/120722600-9c840100-c495-11eb-996a-f6429767a3b7.png)

If it isn't possible for the library to support Three's layering system, let me know. I was hoping to achieve screen space UI and word space UI with this library. For screen space UI, I have a solution similar to how Unity does screen space UI's, where a root canvas lives in the scene and all UI is appended to it, but is rendered via a GUI camera. So any screen space UI would be on one layer, while all other objects are on a separate layer being rendered by the main camera in the scene. I also wanted to be able to support 3D UI rendered by the main camera, at the same time I am rendering any screen space UI. Up to this point, I have achieved this, with my early prototype having a screen space button, and a world space panel (See the image below). Both objects live in the same scene, and are rendered by two different cameras. The only blocker to this concept now is this text issue.

![Screen Space and World Space](https://user-images.githubusercontent.com/83366171/120723750-f5549900-c497-11eb-8fd0-ccc709538dca.png)

My idea is this would easily allow for the UI to be used for both mobile/desktop and VR/AR experiences. One GUI to rule them all 😄. Again, thanks for all your help up to this point, hope this is an easy one!

**Comment by felixmariotto** [comment]
Hey I just had a chance to test, and it's working fine for me, see this fiddle : https://jsfiddle.net/felixmariotto/j9mtrxLy/12/

**Comment by felixmariotto** [comment]
Updates in three-mesh-ui are cascading the component tree from top to bottom, so if you update `Text.textContent` in its parent `Block.onAfterUpdate` callback, your changes will be overwritten right after !

**Comment by JoeCoppola-HIA** [comment]
🤦 Not sure why I didn't think to test that, that is my bad. You are correct, the changes I was making were being overwritten. Thank you for looking into that!
