### ISSUE TITLE
Increase keyboard text size

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [felixmariotto/three-mesh-ui#75]
Hi @felixmariotto,

Is there a way to increase the text font size for the text on the keys of the keyboard at the moment? 
The font size seems fixed.

Let me know if there is a place where I can modify it in the library

Thanks!

**Comment by felixmariotto** [comment]
Hi @SrinivasPrabhu794 ,
Thank you for asking this, you put the thumb on a design issue.
The `Keyboard` component used to set the keys `fontSize` [here](https://github.com/felixmariotto/three-mesh-ui/blob/0baec009571df0b8e26d7138139b364bad8cc78b/src/components/Keyboard.js#L157-L163). I removed the `fontSize` setting from there, so with the latest version ( 4.7.3 ) you can set `fontSize` on the `Keyboard` and it will propagate to the keys.
I updated the keyboard example so it shows how to do it : 
https://github.com/felixmariotto/three-mesh-ui/blob/0baec009571df0b8e26d7138139b364bad8cc78b/examples/keyboard.js#L414
