### ISSUE TITLE
Insert an outline when user clicks on a Block

### ISSUE THREAD

**Issue by kdpkke** [felixmariotto/three-mesh-ui#76]
Hello there. Is there a way or property to activate an outline border when the user clicks on a specific Block (and let it fade away after the click)? Thank you in advance.

**Comment by felixmariotto** [comment]
Hi, there is currently no way to do that, but it would be an interesting feature to add.

**Comment by JoeCoppola-HIA** [comment]
I'd be interested in such a feature. Would a Three BoxHelper be a potential solution for this? 

https://discourse.threejs.org/t/how-can-i-add-an-outline-to-a-plane/10605/8
https://threejs.org/docs/#api/en/helpers/BoxHelper

I suppose the only concern with that would be that Three's docs point out this is mainly for debugging. But this seems like it would be the quickest implementation. 

I figure just like a block has the frameContainer property, maybe Blocks can have a selectionBox property that is initialized if an outline property is set?

**Comment by felixmariotto** [comment]
@kdpkke @JoeCoppola-HIA 

Since it seems there is interest in this feature, I've made a new shader material to add borders : https://jsfiddle.net/felixmariotto/u85nhbkw/1/

I just have to integrate it in three-mesh-ui, it's in progress.

**Comment by felixmariotto** [comment]
Added support for border in version 5.0.0 : https://github.com/felixmariotto/three-mesh-ui/releases/tag/v5.0.0

**Comment by JoeCoppola-HIA** [comment]
@felixmariotto wow this is incredible. Shader solution makes much more sense! Amazing work. I really appreciate your support on this repo. 🍻

**Comment by kdpkke** [comment]
@felixmariotto thank you very much for your work, super fast and very well done!
