### ISSUE TITLE
textureSize in WebGL shaders doesnt work on iOS WebGL 1.0

### ISSUE THREAD

**Issue by lukemonaghan** [felixmariotto/three-mesh-ui#79]
WebGL 1.0 cannot do textureSize which breaks the following shader on iOS devices. 

I don't have a solution as I'm not accustom to WebGL feature set however I believe you have to send it as a uniform for WebGL 1.0.

R.E comment on code line when bug was introduced.
https://github.com/felixmariotto/three-mesh-ui/commit/a01c6744d509bb4b9088ae16d927e6eaddace3b6#r53200878

**Comment by felixmariotto** [comment]
Thank you for reporting, it should be fixed with the version 5.0.2 : 
caaf526
54a54f4
