### ISSUE TITLE
What's the fastest way to update text?

### ISSUE THREAD

**Issue by trusktr** [felixmariotto/three-mesh-ui#8]
Suppose I want to change the font size, or adjust the box size (imagine the user is dragging the edge of the box using a hande, and can resize the box). What's the recommended way to update the UI?

**Comment by trusktr** [comment]
The answer is call `obj.set(options)` and let three-mesh-ui handle the rest! :)

**Comment by trusktr** [comment]
Speaking of performance, I made this example:

https://codepen.io/trusktr/pen/11105a14a0707cc73a67ac62ca5ea6e9

It updates the font size every frame. I found that on my Nvidia Quadro P2000, each frame takes about 27ms.

It is interesting that in the demo, the WebGL font stays perfectly in position while resizing (the math works out well), while the DOM font jumps up and down while it resizes. It seems the native browser font rendering rounds the font positioning to the nearest pixel (aliasing).

**Comment by felixmariotto** [comment]
I think I should mention a few things for clarification on this.

When I designed the update system for the engine, I got inspiration from how html updates itself. There is two types of update : layout update, and paint update.

When updating an attribute of a component that will change its size, it's necessary to update the parents, which may size themselves according to their children. This is the layout update.

When updating an attribute that cannot have any effect on a parent, then it's a paint update, bubbling down to children only, not to parents.

You can see the separation here : 

https://github.com/felixmariotto/three-mesh-ui/blob/6f537fba81ee2edb4931fe67158d7f6e5aac218f/src/core/MeshUIComponent.js#L328-L351

This can be of importance when doing buttons animation for instance, updating colors will perform better.

**Comment by trusktr** [comment]
Nice! That is helpful. Thanks for explaining that.
