### ISSUE TITLE
Block flashing with initial size for single frame on creation

### ISSUE THREAD

**Issue by kalegd** [felixmariotto/three-mesh-ui#83]
Hi, glad to see this project is still up and running! I recently updated to the latest commits and noticed that new Blocks will flash with the initial size for a single frame now. It's due to the updates for the Block not getting applied in the same frame that ThreeMeshUI.update gets called so for the first rendered frame the scale is [1,1,1]

Depending on how fast your computer is you may or may not notice it in this fiddle: https://jsfiddle.net/bevq1szj/3/

I'm not sure if updates are intended to occur synchronously or not for this package? If so, then I think the Promise handling would have to change in UpdateManager. If they are intended to be treated asynchronously, then do you have any recommendations on how to best avoid the initial scale being used for the Blocks first rendered frame? I'm currently just adding `this.frame.scale.set( 0, 0, 1 );` to Line 40 of Block.js as a quick and cheap solution which I could add a PR for easily

**Comment by felixmariotto** [comment]
Hi @kalegd,

The promise handling in updateManager has indeed to be updated, asynchronous turns out to be not ideal. I'm free right now so I will give it a try.

In the meantime you can mitigate the issue by calling `ThreeMeshUI.update()` right after any change to a component : 
https://jsfiddle.net/felixmariotto/0tsyj4dL/1/

**Comment by felixmariotto** [comment]
OK it's fixed with version 5.2.1 : https://jsfiddle.net/felixmariotto/0tsyj4dL/6/
updates are now all asynchronous, and I also set the default Block size to 0, so if you instantiate a Block and set its size and content later, you won't see a 1x1 empty panel in the meantime.

**Comment by kalegd** [comment]
Thanks for getting to this so quickly!! Much appreciated
