### ISSUE TITLE
How to gradually decrease the opacity ?

### ISSUE THREAD

**Issue by gsihaj5** [felixmariotto/three-mesh-ui#87]
i already done this simple script 

``` js
Hotspot.hotspots.forEach(
        (hotspot) => {
            let fadingInterval = setInterval(() => {
                hotspot.setupState({
                    state: "idle",
                    attributes: {
                        backgroundOpacity: hotspot.states.idle.attributes.backgroundOpacity - .01,
                    }
                })
                console.log(hotspot.states.idle.attributes.backgroundOpacity)

                if (hotspot.states.idle.attributes.backgroundOpacity < 0) {
                    clearInterval(fadingInterval)
                    scene.remove(hotspot)
                }

            }, 10)
        }
    )
```
hotspot here is like the button on example. 

i have tried to directly change the backgroundOpacity but the opacity wouldn't change.

is there any other method to work around this ?

**Comment by felixmariotto** [comment]
Hi,

Here is a fiddle showing how to tween the background opacity : https://jsfiddle.net/felixmariotto/j6a2xe3L/3/

As explained [in the doc](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#meshuicomponentsetupstate-options-), `setupState` and `setState`, are used to record a component states and switch between them with less code. It's not really appropriate to tween a value.
