### ISSUE TITLE
hidden overflow - justifyContent: 'left' error

### ISSUE THREAD

**Issue by sylwesterdigital** [felixmariotto/three-mesh-ui#88]
when set on ThreeMeshUI.Block

```
attribute  justifyContent: 'left' 
```
 I have an error:

```
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. 
```
![Screenshot 2021-10-05 at 00 01 24](https://user-images.githubusercontent.com/27820237/135936140-85c2790f-440b-4d55-8308-9620bc55b613.png)

**Comment by felixmariotto** [comment]
hi, `justifyContent: 'left'` is a wrong value, it can only be `'start'`, `'center'` or `'end'`.
