### ISSUE TITLE
Text problem

### ISSUE THREAD

**Issue by immersiontools** [felixmariotto/three-mesh-ui#93]
Hello!

I got weird characters when i use chrome but not on edge or firefox.

![image](https://user-images.githubusercontent.com/55242152/138883866-4568a3ba-41ca-425d-baed-1121a5a6c50b.png)

**Comment by immersiontools** [comment]
Hi, i got this problem on 
Chrome Version 95.0.4638.54 (Build officiel) (64 bits)
Windows 10 (20H2)

**Comment by felixmariotto** [comment]
Mmh this is odd..
I get no issue on Windows 10, Chrome version 95.0.4638.69.

![Screenshot_2](https://user-images.githubusercontent.com/46470486/140180249-8f690900-2843-49d9-bb68-06df64c33b44.jpg)

Would you mind sending screenshots of these pages ? : 
https://webglreport.com/?v=1
https://webglreport.com/?v=2

**Comment by felixmariotto** [comment]
@immersiontools Have you got the issue again ?
Still haven't been able to reproduce on my side.

**Comment by ChaseMillers** [comment]
I have same issue on Chrome. Every example shows text with weird artifacts. Please let me know if anyone finds a fix. 
![image](https://user-images.githubusercontent.com/46936509/148103497-6a26ac67-f92b-4860-9428-0f4c66a46249.png)
![image](https://user-images.githubusercontent.com/46936509/148103515-769904ed-607c-42ee-93d4-3fbe40848e00.png)
![image](https://user-images.githubusercontent.com/46936509/148103588-87a8c3c6-f3d1-4999-ae2b-885e28e29d29.png)
![image](https://user-images.githubusercontent.com/46936509/148103623-9aad6bd9-0a12-44ff-8bf2-0e56dc2a136b.png)
![image](https://user-images.githubusercontent.com/46936509/148103690-367537de-cdf8-4d08-986f-5a2835bb11e2.png)

**Comment by felixmariotto** [comment]
@immersiontools @ChaseMillers We still can't reproduce but we made some changes in `Text` rendering recently, would you mind having a look at the [examples](https://felixmariotto.github.io/three-mesh-ui/#basic_setup) again and tell us it fixed the problem please ?

**Comment by GoncaloBastos** [comment]
Hi @felixmariotto !

One of our users has reported this exact same issue and I can confirm that the latest update solved it for them!

**Comment by felixmariotto** [comment]
@GoncaloBastos glad to hear this !
I still don't really understand what happened and why it's fixed, that's super odd... Anybody feel free to reopen if you still have this problem with latest three-mesh-ui.
