### ISSUE TITLE
[support request] : when to get things ready

### ISSUE THREAD

**Issue by swingingtom** [felixmariotto/three-mesh-ui#95]
Hi, thanks for the library.
When following examples, this works pretty easy. The near rendering is pretty neat 👍 
But as soon as I needed some undocummented uses, it becomes a bit less easy.

I need to retrieve the Mesh inside a Text, but this is not 'instantaneous'

```
let newText = new ThreeMeshUI.Text({
        content: "I'm a text!",
      });

console.log("New Text ",newText.children.length); // no children created yet

// Even after trying somethings that would'nt make sense ( i guess )
newText.updateLayout();
console.log("New Text ",newText.children.length); // nope, still 0 children
```
I ended up using some vicious ways to finally get it

```
let newText = new ThreeMeshUI.Text({
        content: "I'm a text!",
      });

requestAnimationFrame( ()=>{ 
    console.log( newText.children.length ); // Ah, finally get it !
```

But I would like to better understand how things works, before generalising this nextFrame way into my code.
Thanks !

**Comment by felixmariotto** [comment]
Hi, thanks for you interest in the lib !

There is a callback called after any update, it's[ `component.onAfterUpdate`](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#meshuicomponentonafterupdate), which you can also use on `Text` components.
See this fiddle : https://jsfiddle.net/felixmariotto/L8z1c4wj/

Out of curiosity, why do you need to get the characters meshes ?

**Comment by swingingtom** [comment]
Thx for the fiddle. 

It looks a bit weird, the `onAfterUpdate` runs at least two times, but sometimes it goes to up to three times. 
Children are not set in the first onAfterUpdate but usually on the second. 
![image](https://user-images.githubusercontent.com/17314210/140503721-8aa389a4-6e03-4c80-a665-c141fbf443de.png)
It was on chrome at least.

I need to retrieve the Mesh for its usual meshes properties. 
The text I create must go on a specific `Layer`/`Selection` on a specific `.renderOrder`
In my current understanding of Three, `.renderOrder` of `THREE.Object3D` do not cascade the value to each of its children. So I need to explicitely tell each Mesh need to go on which layer at which order. 

I also animate the material opacity property, which is not `instantly` created too. 
By the way, Im unable to animate opacity from the Material property `newText.fontMaterial.opacity`. Even with `.uniformsNeedUpdate=true`. 
I finally worked around using uniforms properties `newText.fontMaterial.uniforms.u_opacity`. 

I might be completely out of scope of the library, even I really really like all the layouting possibilities its offers, I just need to place titles ( as plane ) into a 3d world for now. And perform actions just as I would do on simple planes. I used another library before, but it lacks maintenance. So I give this library a try.

**Comment by felixmariotto** [comment]
> It looks a bit weird, the onAfterUpdate runs at least two times, but sometimes it goes to up to three times.
> Children are not set in the first onAfterUpdate but usually on the second.

`onAfterUpdate` is called everytime the component is updated. When you instantiate the component, it's updated. When you update the component's parent's size, it's updated. Lastly, when the font is loaded, three-mesh-ui knows how to layout the content, so it's updated. That's why the text layout is not instantanuous, how could it be computed before to load the font data ?

> I also animate the material opacity property, which is not instantly created too.
> By the way, Im unable to animate opacity from the Material property newText.fontMaterial.opacity. Even with .uniformsNeedUpdate=true.
> I finally worked around using uniforms properties newText.fontMaterial.uniforms.u_opacity.

Seems to work well on my side, here is a fiddle : https://jsfiddle.net/felixmariotto/2kwbxcL4/24/

**Comment by felixmariotto** [comment]
Also setting the mesh layer was the very reason onAfterUpdate was introduced, see #70
