### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by backface** [felixmariotto/three-mesh-ui#96]
Hi, 

Trying to use this in my vue.js project I get a 

three-mesh-ui.js:21 Uncaught ReferenceError: global is not defined
    at three-mesh-ui.js:21

I can work around it by declaring a global global ( in my entry index.html):

 if (global === undefined) {
    var global = window;
  }

but that does not look like good style to me ;)

I guess three-mesh-ui should check whether it is defined - if it is needed there...

**Comment by felixmariotto** [comment]
fixed by 5.4.2, thank you for reporting.
