### ISSUE TITLE
The UI can be made into a sliding list

### ISSUE THREAD

**Issue by wizVR-zhangjun** [felixmariotto/three-mesh-ui#97]
I want to make a sliding list UI and hope to give some comments

**Comment by felixmariotto** [comment]
Yes three-mesh-ui can be used to create a sliding list.

You should study [this example](https://felixmariotto.github.io/three-mesh-ui/#hidden_overflow)

Another user has done something like this, see [this comment](https://github.com/felixmariotto/three-mesh-ui/issues/62#issuecomment-802976733)

Feel free to open an issue if you have a specific question.
