### ISSUE TITLE
LetterSpacing

### ISSUE THREAD

**Issue by swingingtom** [felixmariotto/three-mesh-ui#98]
Is there a way to have a similar effect as letterSpacing ?
In my case I will try to go with [spaces] between characters, and it should be ok, but im still wondering

**Comment by felixmariotto** [comment]
it's not possible yet but it's a vrey easy feature to add

**Comment by swingingtom** [comment]
Ok great.
If you haven't much time right now, you could always give me a hint to where to start looking.
I can't promise, but at least I can have a look.
 
Thanks

**Comment by felixmariotto** [comment]
Thanks for proposing you help, I'm indeed too busy to work on this...

The module responsible for positioning inlines is [InlineManager](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/InlineManager.js). Every `Block` object is composed with this class. You can see [here](https://github.com/felixmariotto/three-mesh-ui/blob/db2152f90965a78cd80c3016a7cce3c97050f0c9/src/components/core/InlineManager.js#L71-L75) that the `array.reduce` just put the characters side by side according to their width. I suppose you could introduce an additional offset here.

You will have to introduce a new [attribute](https://github.com/felixmariotto/three-mesh-ui/wiki/API-documentation#attributes), so add a getter function in the [base class](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/MeshUIComponent.js) and a [default value](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/utils/Defaults.js) of 0. Then call your getter in `InlineManager` to get your additional offset. Please make sure not to introduce bugs with line breaks, your additional offset should be taken into account when `InlineManager` decides when to break the line.

**Comment by felixmariotto** [comment]
addressed by #104
