### ISSUE TITLE
How can UI text support Chinese

### ISSUE THREAD

**Issue by wizVR-zhangjun** [felixmariotto/three-mesh-ui#99]
I want to display Chinese on the UI. What can I do to solve it

**Comment by felixmariotto** [comment]
Do you mean to dispaly text vertically ?
Or simply to display chinese characters ?

For the former, I'm afraid it's not possible yet. However it should not be very difficult to add this feature.
I suppose we would need to add a new `writingMode` attribute, similar to the CSS `writing-mode`.
If you are willing to file a PR for this feature, the part you should look into and modify is the [InlineManager](https://github.com/felixmariotto/three-mesh-ui/blob/master/src/components/core/InlineManager.js) module.

If you are OK with displaying characters horizontally, simply add the chinese characters in the font files.
[Here is how](https://github.com/felixmariotto/three-mesh-ui/wiki/Creating-your-own-fonts) to make you own font files.

**Comment by felixmariotto** [comment]
closing this, feel free to reopen.
